endlessm/eos-boot-helper

- dracut/repartition/endless-repartition.sh
In our current shipped version of util-linux, "sfdisk --print-id"
actually opens the disk as rw. When it later closes the device,
this causes the kernel to reprobe the partition table in case it
has changed, which can cause udev to recreate device nodes.
This is fixed in the new version of util-linux where this code
has been reworked into a new --part-type option.
Until we upgrade util-linux, add a workaround here: explicitly
asking sfdisk not to write to disk causes it to open the disk
as read-only here.
[endlessm/eos-shell#4771]
> repartition: open disk read-only when checking marker

- Makefile.am
- debian/eos-boot-helper.postinst
- debian/rules
- dev-disk-by\x2dlabel-eos\x2dswap.swap
Move our swap handling out of fstab and into a systemd unit
where we can control it better.
Now swap is purely optional but will be automatically enabled if/when
the appropriate device node appears.
In addition to automake getting it wrong, dh-systemd and systemd-204
also get escaping wrong when enabling this unit (systemd-215 might do it
better). Enable it manually in postinst.
[endlessm/eos-shell#4778]
> Add dynamically activated systemd swap unit

- debian/eos-boot-helper.postinst
Previous iterations of the extra storage resizing services were creating
wants symlinks in /etc/systemd/system to trigger resizing and mounting
on boot. Converted systems without extra storage are now getting boot
delays when these wants chains are enabled.
All that's required for this currently is the
local-fs.target.wants/endless.mount symlink, which is created in the
image builder for split disk images. Remove any old remnants after
installing users upgrading on converted systems.
[endlessm/eos-shell#4880]
> debian: Cleap old extra resizing wants symlinks

- endless.mount
After an ostree upgrade, the /endless mount point directory will be
gone. In that case, we still want systemd to create the directory and
mount the overlayfs there. It will create the mount point if nothing
exists there.
The other 2 conditions remain. The check for /var/endless-extra should
ensure this only runs on split disk units. The check for /endless not
being a symlink should make sure that if the tmpfiles symlink pointing
to /var/endless was somehow created that we don't try to mount a
recursive overlayfs over it.
[endlessm/eos-shell#4912]
> Mount /endless overlayfs when directory doesn't exist

- dracut/repartition/endless-repartition.sh
- eos-extra-resize
util-linux-2.26 removes the -S and -H args from sfdisk.
-uS still exists but is redundant (it only accepts sector addressing now),
so I removed that too.
[endlessm/eos-shell#5261]
> Drop CHS sfdisk args, no longer available

- endless-mount-dirs.service
- endless.mount
Ubuntu's Linux 4.1 (a requirement for eos 2.4.0) does not provide the
'overlayfs' filesystem we have been using before the upgrade, but a
compatibility layer implemented on top of the upstream 'overlay'
filesystem (endlessm/linux@a61b539). Since we're moving to a new
codebase in any case, let's just use the upstream version directly.
For both 'overlay' and 'overlayfs' filesystems there is a 'workdir'
mount option that needs to be passed to rw mounts.
[endlessm/eos-shell#4518]
> Use upstream 'overlay' filesystem

- 50-meson-vdec.rules
- Makefile.am
Chromium looks for the V4L2 video decoder at /dev/mfc-dec. Add
an appropriate symlink for the Meson platform, plus a more appropriate
"meson-vdec" link.
[endlessm/eos-shell#5226]
> Install udev rules for Meson video decoder

- debian/eos-boot-helper.postinst
- debian/rules
- eos-enable-extra-upgrade
- eos-enable-extra-upgrade.service
- eos-extra-resize.service
- var-endless\x2dextra.mount
Some fixes to make app mounts of /var/endless and /var/endless-extra work better.
[endlessm/eos-shell#5414]
> Fixes for app mounts

- eos-enable-extra-upgrade
- eos-enable-extra-upgrade.service
If someone used the single disk image on the EC-200, then the extra
mount unit should not be enabled. Use the presence of
/var/eos-extra-resize to signal that the extra filesystem has been
created and should be mounted.
[endlessm/eos-shell#5481]
> eos-enable-extra-upgrade: Only run when /var/eos-extra-resize exists

- eos-enable-extra-upgrade
Previously, an overlayfs was mounted at /endless and statically enabled
through a symlink to its endless.mount unit. If it's now dangling, clean
it up.
[endlessm/eos-shell#5593]
> eos-enable-extra-upgrade: Clean up dangling endless.mount link

- eos-enable-zram
This impacts current development kernels which have everything built-in
and therefore lack the 'zram' module.
[endlessm/eos-shell#6376]
> Don't try to load zram if it is already loaded

- dracut/repartition/endless-repartition.service
systemd-229 includes a special condition where it generates the fsck
unit with name "systemd-fsck-root.service" if we are in the initramfs
and dealing with /sysroot.
Update our dependencies accordingly to fix a sequencing problem during
boot.
https://phabricator.endlessm.com/T11323
> endless-repartition: update for new root fsck service

- dracut/repartition/endless-repartition.service
- dracut/repartition/endless-repartition.sh
To move away from having the root filesystem always identifed by a fixed
label, update endless-repartition.sh to query sysroot.mount for the root
device.
That introduces a complication in the service file, we can no longer
order after a fixed device such as dev-disk-by\x2dlabel-ostree.device.
To make this unit run after the root device becomes available, but before
fscking it, we would have to likely modify systemd's generators so that
the availability of the root device triggers a new target, which
endless-repartition could be a part of.
But there's no strong requirement for us to run before fsck. We can
instead run after fsck, at which point the root device is guaranteed to
be ready.
https://phabricator.endlessm.com/T11392
> repartition: detect root device from systemd

- Makefile.am
- debian/rules
On 8bcfe86e6b68c24f8d6f00114152e3fe7b7f688a we created a new unit to
mount the "ostree-boot" partition on /sysroot/boot on systems that ship
a separate boot partition, but we forgot to modify the build system to
install this file, and the packaging system to enable this unit on the
final image.
https://phabricator.endlessm.com/T11157
> T11157: Install and enable sysroot-boot.mount

- dracut/repartition/endless-repartition.sh
Boot often hangs after repartitioning because the recreation of the
block device nodes causes systemd to cancel important parts of the
initramfs boot procedure.
Retriggering initrd.target solves this. Retriggering like this is also
done in other parts of the boot process like in initrd-parse-etc.service.
https://phabricator.endlessm.com/T11323
> repartition: Retrigger initrd.target

- dracut/repartition/endless-repartition.service
We recently moved away from identifying the root device by a fixed
label, which caused us to rethink the boot order position: we placed
repartition after fsck.
That didn't work out as intended; during repartitioning, the disk device
will disappear and return, and upon it's return, systemd was running the
fsck unit while repartitioning was still ongoing.
Use the new initrd-root-device.target to order ourselves exactly where we
need to be: root device available, not yet fscked, not yet mounted.
https://phabricator.endlessm.com/T11323
> repartition: order after root-device, before fsck-root

- dev-disk-by\x2dlabel-eos\x2dswap.swap
When installing on systems with EOS already installed, this unit enables the swap on the HDD and makes the install fail.
> disable eos-swap on eosinstaller images

- Makefile.am
- debian/eos-boot-helper.postinst
- debian/rules
- dev-disk-by\x2dlabel-eos\x2dswap.swap
Recent systemd (229+) GPT generator automatically detects and activates
swap partitions on the same device the system has booted from, so we
don't need to ship a swap unit.
https://phabricator.endlessm.com/T11761
> Don't ship a swap unit anymore

- dracut/repartition/endless-repartition.sh
- dracut/repartition/module-setup.sh
- eos-firstboot
We're facing some strange filesystem corruption on first boot, which
goes away if these commands are commented out.
The tune2fs man page warns about changing uninit_bg:
After setting or clearing sparse_super, uninit_bg, filetype,  or
resize_inode  filesystem  features, e2fsck(8) must be run on the
filesystem to return  the  filesystem  to  a  consistent  state.
Tune2fs will print a message requesting that the system adminis‐
trator run e2fsck(8) if necessary.
Things don't quite add up: tune2fs does not ask us to run e2fsck,
the corruption that is seen on first boot is really extensive (not just
related to uninitialized bitmaps), and running these commands manually
later also doesn't cause the problem to come back.
Regardless, seems like doing this here is a bad idea.
We'll move the …
> firstboot: filesystem UUID is now randomized in initramfs

- Makefile.am
- configure.ac
- dracut/Makefile.am
- dracut/endless.conf
- dracut/image-boot/Makefile.am
- dracut/image-boot/eos-image-boot-generator
- dracut/image-boot/eos-image-boot-setup
- dracut/image-boot/eos-image-boot-setup.service
- dracut/image-boot/eos-live-etc-setup.service
- dracut/image-boot/module-setup.sh
- dracut/repartition/endless-repartition.service
- dracut/repartition/endless-repartition.sh
- dracut/repartition/module-setup.sh
- eos-firstboot.service
- eos-live-boot-overlayfs-setup
- eos-live-boot-overlayfs-setup.service
Add infrastructure needed to support booting from an Endless image file
found on an exFAT partition. This is primarily implemented inside the
new eos-image dracut module.
The endless.image.device parameter should be generated by the bootloader,
either specifying the PARTUUID= of the partition that contains the Endless
image.
The endless.image.path parameter provides the path to the image file on
that filesystem.
A new generator handles these parameters and hooks up the final block
device setup to the normal systemd initramfs fsck/mount infrastructure.
The block device setup script identifies which disk extents are occupied
by the image file and creates a linear device-mapper device that
corresponds. This is easier and much better performing than going through
exfat-fuse.
The …
> Support booting from image file on exFAT

- eos-repartition-mbr
This script is to be run from eos-installer. It's easy to get the disk
device path there – we just wrote the disk image to it! – but harder to
decide whether it just needs to append '3', or whether it needs 'p3'.
https://phabricator.endlessm.com/T12793
> eos-repartition-mbr: accept disk device, not partition

- 10-allow-mounting-endless-image-device.rules
- Makefile.am
- dracut/image-boot/eos-image-boot-generator
- eos-image-boot-dm-setup
- eos-image-boot-dm-setup.service
We are mapping the partition passed in the `endless.image.device=` kernel command line argument to a device mapper device called `host`, and installing the necessary polkit rules to allow for regular users to mount it through the file manager (so a dual-boot user can access its files on the windows partition).
When setting up the dm device, we're mapping the blocks where `endless.img` lives to `error`, so any I/O attempt on them through this dm device fails, adding an additional layer of protection to `endless.img`. This implies that the flasher tool will have to read from dm device which maps `endless.img` and not from the `endless.img` file. Reading from the dm device also should have a better performance than reading from the `endless.img` file, since we will not have to go through …
> Provide read-only access to the filesystem hosting endless.img

- eos-enable-extra-upgrade
- eos-enable-extra-upgrade.service
We want /var/endless-extra to be mounted before local-fs.target
completes. In order to ensure that happens on upgrades from old systems,
we need the eos-enable-extra-upgrade service to run early so that the
local-fs.target.wants link for var-endless\x2dextra.mount has been
created.
Rework the dependencies and ordering so that the service can run after
normal mounts are done but before var-endless\x2dextra.mount. With the
service part of local-fs.target, the script no longer needs to manually
start the mount unit. That seems to result in a deadlock.
https://phabricator.endlessm.com/T12747
> eos-enable-extra-upgrade: Run before local-fs.target

- eos-enable-extra-upgrade
- eos-enable-extra-upgrade.service
- eos-enable-zram.service
Backport fixes for handling the /var/endless-extra mount after upgrading from a system where /endless was an overlayfs mount.
https://phabricator.endlessm.com/T12747
> Handle /var/endless-extra on upgrade correctly

- eos-image-boot-dm-setup
This should be safe now we have logic to guard the image file in
exfat-fuse and ntfs-3g. In the dual-boot case, this allows users to
delete files from their Windows drive to their heart's content! In the
combined USB case, this allows us to (potentially) save a debug log to
the image device.
https://phabricator.endlessm.com/T13136
> Allow mounting endless-image-device rw

- dracut/image-boot/eos-image-boot-generator
When booted from a pristine image (on USB), one of the options presented
to the user is to run eos-installer to overwrite the system's hard drive
with the booted pristine image.
In eos-installer, we cannot read /endless/endless.img from the DM device
mapped over the host partition, because its sectors are blocked out with
'error'. Even if we could, we expect reading the mapped 'endless-image'
device to be substantially faster than going via FUSE.
By default, the mapped device will be owned by root:disk with
permissions 0660, so eos-installer (running as gnome-initial-setup or
the live user) cannot read it. It cannot be opened with UDisks'
OpenForBackup() method, which is documented to not support opening
devices which are in use (it passes O_EXCL to open(2) to implement
this). If we were …
> image-boot-generator: make endless-image world-readable

- eos-live-boot-overlayfs-setup
If 'endless.live_boot' is on the command line, we pass '--readonly' to
dmsetup when mapping endless-image, and we mount it on /sysroot with the
'ro' flag. So, we don't need to overlay it with a tmpfs to protect it
from modification.
We need to mask:
* /sysroot/flatpak
* /sysroot/home (symlinked from /var/home and /home)
* /sysroot/ostree
as all these potentially need to be written to.
A side-effect of leaving /sysroot untouched is that we can successfully
read xattrs from it -- specifically, the eos-image-version attribute,
used by eos-phone-home (and other applications).
https://phabricator.endlessm.com/T13741
> T13741: live boot:  don't overlay /sysroot in its entirety

- eos-live-boot-overlayfs-setup
This depends on a patch in our kernel to add the user_xattr flag in the
first place.
https://phabricator.endlessm.com/T13817
> live-boot: enable user xattrs on /run

- eos-repartition-mbr
The idea behind T12365 is that there are some systems which will not proceed to boot a hard drive unless they have an DOS partition table with one partition marked as bootable. T12793 does the hard work of converting the GPT partition table to a DOS partition table.
However, unfortunately we don't set any of our nice new DOS partitions as bootable... meaning the affected systems that this work was aimed to support can still, in fact, not boot our OS. Oops.
https://phabricator.endlessm.com/T14243
> eos-repartition-mbr: mark the root partition as bootable

- dracut/repartition/endless-repartition.sh
I noticed the following in a log from Mures working on ISO booting:
endless-repartition[229]: /bin/endless-repartition: 94: [: unexpected operator
endless-repartition[229]: sfdisk: cannot open /dev/mapper/endless-image: No such file or directory
endless-repartition[229]: repartition: marker not found
If $pt_label is empty, `[ "$pt_label" == "dos" ]` causes `[` to fail
with the above error message. Let's fail explicitly in that case, rather
than falling through to an `sfdisk` incantation that will also probably
fail.
> repartition: cope with blkid returning an empty string

- dracut/repartition/endless-repartition.sh
- eos-extra-resize
Accept all devices ending with "p" then a number.
This will cover existing MMC cases (e.g. mmcblk1p3) and also
NVMe (e.g. nvme0n1p3).
https://phabricator.endlessm.com/T14393
> repartition: Add support for NVMe block devices

- Makefile.am
- eos-fix-flatpak-branches
- eos-fix-flatpak-branches.service
For 3.0.10 and 3.0.11, the image builder was changed so that it
installed from the eos3.0 refs instead of the eos3 refs so that there
wasn't interference from eos3.1. To make it look like eos3 apps were
installed, the app checkout directories were changed to look that way.
Unfortunately, the branch is also embedded in the desktop file when
flatpak exports it, and this was not updated.
Provide a boot service that tries to find and fix these desktop files.
This will run only on upgrade.
https://phabricator.endlessm.com/T15005
> Provide service to fix broken flatpak desktop files

- var-endless_x2dextra.mount
RequiresOverridable= has been replaced by Requires=, which has basically
equivalent functionality unless a user starts the unit manually, which
we don’t expect for this mount unit.
See upstream systemd commit f32b43bda454a70ae23d6802605d41b26dc24ce2.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T15452
> extra.mount: Fix use of deprecated systemd unit file key

- eos-add-flatpak-gnome-repos
This is a temporary fix to set a title for those repos in images that
already included configured, but failed to specify the title at the
time of building it (previous to eos 3.1.2).
https://phabricator.endlessm.com/T15580
> Make sure the title is set for GNOME flatpak repositories

- eos-image-boot-dm-setup
If there happens to be a hole just before the end of the disk, `mount`
and friends try to read it while probing the filesystem type. This
fails, so the drive can't be mounted. (`mount -t ntfs-3g
/dev/mapper/endless-image-device /mnt` works fine -- it is not ntfs-3g
which is reading inside the holes.)
The 'zero' dm target returns zeros when read and discards all writes,
like /dev/zero.
https://phabricator.endlessm.com/T15818
> image-boot-dm-setup: use zero, not error, for holes

- eos-live-boot-overlayfs-setup
This timer was renamed, and so the mask no longer applies. Instead,
we'll add an endless.live_boot condition directly to the timer.
https://phabricator.endlessm.com/T15977
> Don't mask eos-updater.timer

- configure.ac
- dracut/Makefile.am
- dracut/customization/Makefile.am
- dracut/customization/eos-install-custom-boot-splash
- dracut/customization/eos-install-custom-boot-splash.service
- dracut/customization/module-setup.sh
- dracut/endless.conf
Mechanism to ship image-specific customizations in the initramfs. For
now provides boot splash animation customization support.
https://phabricator.endlessm.com/T15989
> dracut: Create customization module

- dracut/repartition/endless-repartition.sh
Similarly to the recovery partition, if we detect a basic data partition
we'll only occupy the space that leads up to it, and leave that partition
intact.
https://phabricator.endlessm.com/T16442
> Allow coexistance with basic data partition at end of disk

- dracut/repartition/endless-repartition.sh
Shell syntax failure, can't have multiple matches without using |
on the same line.
Move back to the if style and wrap the test naturally onto 2 lines.
https://phabricator.endlessm.com/T16442
> repartition: Fix detection of basic data partition

- dracut/repartition/endless-repartition.sh
We try to preserve a single trailing partition of type Basic Data
or OEM Recovery on the disk. However, previously, if there was not
enough space to create a swap partition between the root partition and
the preserved partition, we would format the trailing partition as swap.
The logic was simply: if a partition numbered one greater than the root
partition exists, call mkswap on it.
By explicitly unsetting $swap_part when we are not creating a swap
partition, we avoid this problem: the partition-exists test fails and
mkswap is not called.
https://phabricator.endlessm.com/T16442
> repartition: don't format any trailing partition as swap

- dracut/repartition/endless-repartition.sh
- tests/Makefile.am
- tests/test_repartition.py
This test was useful for me in fixing a bug in this script --
https://phabricator.endlessm.com/T16442 -- but has the major limitation
that it must be run as root (or another user able to run `losetup`). I had
hoped that I could test a subset of the script by running `sfdisk` on a
file, but that would not expose the bug in question (a logic error in later
stages of the script).
> repartition: add a test

- 10-allow-mounting-endless-image-device.rules
Previously, a standard user (such as the passwordless `shared` user) could mount the partition hosting the `endless.img` file without any authentication. On a dual-boot system, this is the Windows `C:` drive.  We do not enforce any per-file access controls within the NTFS partition (it's hard to map between Windows and Endless OS users, we don't even try) so this allowed a non-admin user on Endless OS to read and write any file on the Windows drive.
With this change, only administrators will be able to mount the image host partition without authentication. If a standard user tries to mount it, they're asked to authenticate with an administrator's password.
If `alice`, an administrator, mounts the device, and `bob`, a standard user, logs in on VT2, `bob` cannot access the mounted device …
> Only allow admins to mount image host partition

- Makefile.am
- debian/rules
- eos-fix-home-dir-permissions
- eos-fix-home-dir-permissions.service
Starting with 3.1.6, we default to dir mode 700 for any
new user home directories, but previously we followed
the debian default of 755.
This service runs once after an upgrade from any version
prior to 3.1.6, to change the dir mode of any existing home
directories from 755 to 700.  Once run, a stamp file is
created to avoid running again, so that any further
tweaks by an admin to directory permissions will not be undone.
https://phabricator.endlessm.com/T16858
> Add eos-fix-home-dir-permissions

- Makefile.am
- eos-migrate-image-defaults
- eos-migrate-image-defaults.service
Simple systemd unit and script to check if /var/eos-image-defaults
is a directory (and not a symlink), move it to /var/lib, and make
a compatibility symlink.
https://phabricator.endlessm.com/T15704
> add eos-migrate-image-defaults script & service

- dracut/image-boot/Makefile.am
- dracut/image-boot/eos-image-boot-setup
- dracut/image-boot/eos-map-image-file
- dracut/image-boot/module-setup.sh
- tests/Makefile.am
- tests/check-syntax
- tests/run-tests
- tests/test_image_boot.py
- tests/test_repartition.py
- tests/util.py
I'm working on making the Installer for Windows operate on ISOs rather than on raw disk images, and I'm hoping to improve the USB stick creation process at the same time.
For starters: many users are surprised that they need a 32GiB USB stick for many Full images, despite the (compressed) download size being less than 16G(i)B. Even if we keep the current approach of putting the image file within a big exFAT partition on the USB stick (which is good, because it keeps the free space on the USB stick usable), it'd be nice if we could put the squashfs from inside the ISO onto that exFAT partition.
It'd also be nice to be able to reuse more of Rufus's USB stick creation code. Ours is a bit unreliable on Windows; of course, all bugs can be fixed, but if we can just lean on Rufus' (presumably) …
> image-boot: support squashfs on exFAT

- tests/check-syntax
It's always the simple changes... Using `git grep` in `tests/check-syntax` is not going to work when building from a tarball.
https://phabricator.endlessm.com/T15890
> fix make distcheck

- debian/rules
The purpose of `override_dh_systemd_enable` here is to pass `--no-enable` for `eos-firewall-localonly.service` but enable all other services. But listing the `.service` files directly is error-prone -- it means that any new `.service` files added to the package need to be added to this list too. `eos-add-flatpak-apps-repos.service` and `eos-migrate-image-defaults.service` were not included here when they were added to the package, so did not run on converted systems.
When invoked without any unit files, `dh_systemd_enable` operates on all units installed by the package which contain an `[Install]` section.  Debhelper provides a `-X` option which can be used to exclude items from processing. This better expresses the intent of this rule -- enable all services, except …
> debian/rules: remove extra list of .service files

- dracut/image-boot/eos-live-early-overlayfs-setup
- eos-image-boot-dm-setup
- eos-live-boot-overlayfs-setup
- eos-live-boot-overlayfs-setup.service
ostree's behaviour around mounting `/var` changed https://github.com/endlessm/ostree/commit/05d0ee5cbecd1287b87d38e969862a5d8b1f2e58 https://github.com/endlessm/ostree/commit/30705889cb867c18cdb7fed8e55dc46477c069fa and as a result, `/var` does not have the correct contents on live boots any more. Here, I attempt to fix this.
Tested by rebuilding the initrd and copying it and the other changes into the image on a combined USB.
https://phabricator.endlessm.com/T17622
> Fix /var on live boots with new ostree

- Makefile.am
- eos-add-flatpak-apps-repos
- eos-flatpak-change-origin
When adding the new eos-sdk repo after an upgrade, make sure the only
installed copy of EknServices is the one published there. (We assume
that there is an internet connection since this script runs when we just
completed an OS upgrade.)
We remove any orphaned refs belonging to the old
com.endlessm.EknServices, though normal users would not have these
anyway.
https://phabricator.endlessm.com/T17863
> Install com.endlessm.EknServices from eos-sdk

- eos-add-flatpak-apps-repos
This should fix this job intermittently failing on some boots.
https://phabricator.endlessm.com/T17172
> eos-add-flatpak-apps-repos: ensure temp files are flushed before use

- eos-add-flatpak-apps-repos
Per @cosimoc's review, make the script more robust against unusual
system configurations and user interaction by iterating over both
Flatpak deploy paths and attempting to migrate any EknServices
deployments found in either place.
https://phabricator.endlessm.com/T18287
> look for EknServices in both Flatpak system paths we use

- eos-live-boot-overlayfs-setup
Without this change, setup_ostree_flatpak_overlay fails with:
rm: cannot remove ‘/var/lib/flatpak’: Read-only file system
ln: failed to create symbolic link ‘/var/lib/flatpak/ostree’: Read-only file-system
This is because /var is not yet read-write.  The result is that apps
cannot be installed in a live system.  This regression is a combination
of an ostree behaviour change and an incorrect adjustment for that
change in 3dda953 / PR #114.
https://phabricator.endlessm.com/T18477
> live-boot: set up ostree+flatpak overlay after /var overlay

- eos-add-flatpak-apps-repos
Due to a bug in eos-image-builder, all the com.endlessm.apps.* runtimes
wound up with their remotes pointing to eos-runtimes, not eos-sdk. This
adds a correction to the boot helper script.
https://phabricator.endlessm.com/T18366
> eos-add-flatpak-apps-repos: Set correct remotes

- Makefile.am
- eos-remove-legacy-external-apps
- eos-remove-legacy-external-apps.service
Since we no longer use the external apps implementation we did for
pre-3.1 releases, we should make sure that our users are not left
with runtimes occupying space, and the external apps remote just
resulting in potential bugs.
https://phabricator.endlessm.com/T14442
> Clean up the legacy external apps remote and runtimes

- 50-eos.preset
- Makefile.am
- configure.ac
- debian/control
We are currently wasting resources re-building systemd and
re-distributing all of systemd packages every time we change the preset
file. Let move it to a smaller package.
https://phabricator.endlessm.com/T11144
> Import eos.preset from systemd package

- eos-live-boot-overlayfs-setup
This will be used by test/demo modes to also overlay /etc.
https://phabricator.endlessm.com/T18999
> live-boot: allow passing a list of extra overlay mounts

- Makefile.am
- eos-link-host-mali-driver
- eos-link-host-mali-driver.service
This symlinks the host GL Mali driver in
/usr/lib/arm-linux-gnueabihf/mali400-egl-x11 into a place where Flatpak
will hopefully look for it and mount it as an extension. This makes the
separate org.freedesktop.Platform.GL.mali450-blah-blah extension
unnecessary, as we can simply use the host's driver.
https://phabricator.endlessm.com/T18288
> eos-copy-host-mali-driver: Put GL driver in extension

- eos-add-flatpak-apps-repos.service
- eos-add-flatpak-flathub-repos.service
- eos-add-flatpak-gnome-repos.service
- eos-ostree-remotes-config
- eos-ostree-remotes-config.service
- eos-remove-legacy-external-apps.service
Set the repo config option core.add-remotes-config-dir repo option to
false so that new remotes are not added in /etc/ostree/remotes.d. Adding
them there is incompatible with the way flatpak modifies remotes and
will cause the repo to become unusable. Setting that option to false
ensures that ostree only adds remotes in the repo's config file.
This might only needed temporarily until ostree and flatpak get updated
to do sane remote modification.
The service is only run on updates and before any known /ostree/repo
services. The other services here that modify the repo are setup to run
after this service. That was done to increase the likelihood that new
services copied from those will also run after this service.
https://phabricator.endlessm.com/T19077 …
> Add service to prevent adding ostree remotes in /etc/ostree/remotes.d

- Makefile.am
- configure.ac
- dracut/endless.conf
- nouveau.conf
- nvidia-graphics-cleanup
- nvidia-graphics-setup
- nvidia-graphics.service
As nouveau is not supporting the latest nvidia hardware well enough,
we will now activate the nvidia driver automatically, when we detect
supported hardware.
Detection is done using PCI IDs, using the same technique
as Debian.
We have to remove nouveau from the initramfs, and blacklist it on
the real root, in order to stop it being loaded, since otherwise
we cannot unload it (to then load nvidia).
However, if nvidia load then fails, we fall back to nouveau.
We also fall back on nouveau if the user has blacklisted
nvidia in the regular modprobe configuration.
https://phabricator.endlessm.com/T19190
> Activate nvidia graphics driver on supported hardware

- eos-link-host-mali-driver
- eos-link-host-mali-driver.service
With the work to support NVIDIA binary drivers we had to move our Mali
drivers to a different location. We need to adjust paths here
accordingly, overwriting the old link in case it exists.
ConditionPathExists= follows symbolic links, so the service will run
when upgrading on a system which already has the system pointing to the
old location.
https://phabricator.endlessm.com/T18579
> eos-link-host-mali-driver: Fix host path

- nvidia-graphics-setup
If the nvidia modules have dependencies which are not already
loaded, insmod will fail.
This was seen on Asus GL503VM because drm was not loaded (needed by
nvidia-drm).
Parse the nvidia module dependencies and try to load them first.
https://phabricator.endlessm.com/T19190
> nvidia-graphics-setup: handle module dependencies

- eos-image-boot-dm-setup
- tests/test_image_boot.py
I needed to run this script by hand while working on eos-installer; and once it's been made to accept arguments, it's easy enough to write a test.
https://phabricator.endlessm.com/T18706
> Test eos-image-boot-dm-setup

- eos-link-host-mali-driver
Our mali driver is compiled against a patched X11 library that has a
new symbol (XDisplaySetErrorHandler) which will not be present in
flatpak runtimes
Since we can not currently rebuild the driver the only solution is to add
a wrapper library that links with the driver and implements the missing symbol
https://phabricator.endlessm.com/T18288
> eos-link-host-mali-driver: add libMali wrapper to fix missing symbol

- Makefile.am
This fixes a build-failure fallout from the last PR.
https://phabricator.endlessm.com/T18676
> build: Remove leftover reference to nvidia-graphics-cleanup

- eos-add-flatpak-apps-repos
Fix the broken subpath introduced in the image builder during 3.2 on sea (South-East Asia) OEM images. Detect only this value in the .Locale deploy files and replace it with the correct list, so that the next time this extension is upgraded, the right subpaths are deployed.
https://phabricator.endlessm.com/T19472
> T19472: eos-add-flatpak-apps-repos: fix corrupted /en,id,th,vi subpath

- Makefile.am
- eos-setup-flatpak-extension-dir-extra.service
On non-split systems /var/endless-extra does not exist, so if try to
create this symlink through a static tmpfile, systemd-tmpfiles returns
an error (although the other files are created correctly), causing
systemd-tmpfiles-setup.service to exit with a failure status.
Let's use a simple service unit to create it only on split-disk systems.
https://phabricator.endlessm.com/T19691
> Setup flatpak extension directory on extra storage

- Makefile.am
- nvidia.conf
We found problems when trying to run flatpak apps that use the 3.2
runtime on systems where the nvidia driver is loaded. This disables
automatically loading the nvidia driver for now.
https://phabricator.endlessm.com/T19581
> Disable loading nvidia module by default

- eos-remove-old-flatpak-extension-dir-extra.service
- eos-setup-flatpak-extension-dir-extra.service
If the link already exists we don't need to spawn ln.
https://phabricator.endlessm.com/T19691
> Don't run eos-setup-flatpak-extension-dir-extra on every boot

- eos-setup-flatpak-extension-dir-extra.service
This actually lives in /bin, not /usr/bin. Even tho /bin is a symlink to
/usr/bin, if we ever change this, or need to run this script on a
different setup for some reason, it is better to use the correct path.
https://phabricator.endlessm.com/T19691
> Fix ln path

- debian/control
Although we're almost certain to have almost all of these, on ARM
systems without eos-{application,browser}-tools the systemd journal
python bindings were not installed, causing eos-add-flatpak-apps-repos
to fail.
https://phabricator.endlessm.com/T19472
> add missing package Depends

- nvidia-graphics-setup
If present, we will now attach a signature to the modules we link.
The idea here is that the module linking is reproducible,
and the signature which we attach will be trusted and let the kernel
load the module even when secure boot is enabled.
https://phabricator.endlessm.com/T19170
> Attach secure boot signatures to modules

- eos-repartition-mbr
- tests/Makefile.am
- tests/test_repartition_mbr.py
Previously, we removed it from the partition table. But in practice it is relatively common for users (and Endless developers!) to boot from USB stick in legacy mode, which causes eos-installer to run this script after writing the image to disk, then attempt to boot the installed system in UEFI mode.
Instead, we preserve the ESP, using the 'EF' partition type.  This is the same partition type we and others use in our MBR-only hybrid .iso images, so it's expected that the majority of UEFI systems will be able to boot it.  (eos-installer still prefers to leave the disk in GPT format if it know the system is UEFI.)
We also leave the BIOS bootloader where it is (in the now-unpartitioned space between the ESP and the ostree partition) rather than reinstalling it at the start of the disk. See …
> eos-repartition-mbr: preserve ESP

- eos-add-flatpak-apps-repos
Introduces a new function into eos-add-flatpak-apps-repos which allows us to
provide an array of flatpak names (either apps or runtimes) which are matched
by branch and/or origin, and moved atomically to the new branch and/or origin
as requested.
Changing the origin is achieved with our existing code for rewriting deploy
files, and changing the branch is done by hardlinking the old deploy folder
to the new branch name, and updating the "current" symlink if it's an app
(runtimes have no current symlink as they are always referenced using the
branch name).
This means we can move Steam from the eos-apps origin to flathub, and update
the branch from eos3 to stable. The user can then upgrade their Steam and get
working 32-bit NVidia drivers from upstream Flathub.
This branch picks two commits …
> T20322: migrate Steam from eos-apps to flathub

- eos-update-flatpak-repos
Erase the old gnome-apps remote, and move all org.gnome.* apps to
the flathub remote by adding prefix matching support to the migration
list. The branch is the same on both repos, "stable".
https://phabricator.endlessm.com/T19898
> eos-update-flatpak-repos: migrate gnome-apps to flathub

- Makefile.am
- eos-companion-app.service
- eos-companion-app.socket
- tmpfiles.d/eos-companion-app-helper.conf
This will listen on port 1110 to launch the Companion App, if available.
https://phabricator.endlessm.com/T20130
> service: Add eos-companion-app.service and socket activation

- eos-update-flatpak-repos
These two are particularly broken in eos-apps and this is causing
problems for our OEM partners. Fixes a bug elsewhere in the
script.
https://phabricator.endlessm.com/T20411
> T20411:  eos-update-flatpak-repos: switch TeeWorlds and MegaGlest to flathub

- eos-update-flatpak-repos
- flatpak-repos/Makefile.am
- flatpak-repos/gnome.flatpakrepo
Remove the 'gnome' remote and migrate the fd.o 1.6 and gnome 3.2[46]
runtimes to the 'flathub' remote. Fix a small bug in attempting to migrate
prefix-matched runtimes multiple times.
https://phabricator.endlessm.com/T20443
> remove 'gnome' remote and migrate runtimes

- nvidia-graphics-setup
Some BIOSes (like the Asus GL502VS) disable the HDMI audio device
during boot. Nvidia showed how this can be controlled by a bit in
PCI extended configuration space.
Under Windows, this bit appears to be managed according to whether a
HDMI cable is connected or not.
Until this issue is better solved in the driver, attempt to detect
this case and apply the workaround before loading the driver.
https://devtalk.nvidia.com/default/topic/1024022/linux/gtx-1060-no-audio-over-hdmi-only-hda-intel-detected-azalia
https://bugs.freedesktop.org/show_bug.cgi?id=75985
https://phabricator.endlessm.com/T20286
> nvidia-graphics-setup: enable HDMI audio device

- Makefile.am
- eos-fix-external-appstream
- eos-fix-external-appstream.service
EOS downloads an external appstream file "eos-extra.xml" every time
there's a refresh and the server's file is younger than the cached one.
We ship a version of eos-extra.xml in the images as a base point but the
name used to store the file no longer corresponds to the one GNOME
Software generates: it should now take an "org.gnome.Software-" prefix.
So this patch creates a service to rename or remove that file.
https://phabricator.endlessm.com/T19319
> Add eos-fix-external-appstream

- eos-update-flatpak-repos
Move these apps from eos-apps to flathub:
com.google.AndroidStudio
com.slack.Slack
com.spotify.Client
com.transmissionbt.Transmission
net.minetest.Minetest
org.freeciv.Freeciv
org.gnome.Builder
org.gnome.Genius
org.gnome.Gnote
org.inkscape.Inkscape
org.pitivi.Pitivi
org.tuxpaint.Tuxpaint
org.videolan.VLC
org.wesnoth.Wesnoth
https://phabricator.endlessm.com/T20724
> migrate remaining eos-apps to flathub where app ID matches

- 50-usb-mouse-wakeup.rules
Acer Desktop team requests that the USB mouse is enabled as a wakeup
source, matching the behaviour of Windows.
To minimize impact and unwanted wakeups, we add a rule for Mini PC
chassis type.
https://phabricator.endlessm.com/T20671
> Enable USB mouse wakeup on Mini PC systems

- nvidia/dmi-blacklist
These systems are also believed to have the nvidia 940MX/MX110/MX130
suspend/resume issue.
https://phabricator.endlessm.com/T20647
> nvidia: blacklist more Asus NVIDIA GM108 systems

- 50-usb-mouse-wakeup.rules
More chassis type added to enable usb mouse wakeup per Acer Desktop
team request.
https://phabricator.endlessm.com/T20785
> Enable USB mouse wakeup on AIO and Stick PC systems

- Makefile.am
- eos-extra-target-generator
- eos-fix-flatpak-branches.service
- eos-update-flatpak-repos.service
Introduce a new eos-extra-settled.target to address race conditions when
running eos-update-flatpak-repos on "split" systems where the default
flatpak system dir is provided by an SD card mounted at /var/endless-extra.
The problem is that (by design) the local-fs.target is not blocked by the
availability of /var/endless-extra so that systems can boot properly when
the SD card is unavailable - whether missing, damaged or corrupted - the
only symptom is the availability of the apps installed there, but the rest
of the system works OK.
If the discovery of the SD card is slow enough, or it's being resized or
fscked, the /var/endless-extra mount job isn't in the queue when the
eos-update-flatpak-repos job is evaluated, so the After= has no effect
and the job runs before /var/endless-extra is …
> T20443: fix race of eos-update-flatpak-repos with mount of extra SD card

- 50-eos.preset
On ostree systems, the associated .service units will always fail when
triggered. So, arrange for them to be disabled by default.
It is a little sad that this applies to converted systems where these
timers actually are useful. An alternative would be to add
ConditionKernelCommandLine=!ostree
to apt-daily{,upgrade}.{timer,service} in the 'apt' package (or as
drop-ins in UNIT.d/ostree.conf files) but as discussed in
https://phabricator.endlessm.com/T18831#470667 this would impose more
maintenance overhead in future unless we were to push this change
upstream.
https://phabricator.endlessm.com/T18831
> 50-eos.preset: Disable apt-daily{,-upgrade}.timer

- nvidia/dmi-blacklist
The NV GTX 1050M of FX570UD and NV MX150 of V272UN cannot resume back
from suspend with the normal display when use the nvidia driver (ver. 390.25).
If we ssh into the system, we can find that X takes the CPU resource almost
100%.
So, change the driver to nouveau which can solve the problem.
https://phabricator.endlessm.com/T21413
> dmi-blacklist: ASUS FX570UD & V272UN can't using nv drv

- eos-enable-zram
- eos-enable-zram.service
Currently zram is only enabled for ARM systems with 1 GB of memory or
less. This commit enables zram for all architectures and all amounts of
memory, as long as disk-based swap isn't already in use. Here are some
of the reasons for the change:
- Currently, 1 GB, 2 GB, and even 4 GB systems can quickly become
unusable when the memory load is high (especially with Chrome).
- There are efforts underway to reduce memory usage and make the OOM
Killer more aggressive, but this strategy can coexist with those.
- In the testing over the last few days mostly on Weibu F3C and HKC N11C
computers, having a large amount of zram available allowed a
significantly higher workload than a small amount or none.
- On the Weibu, the performance with zram is slightly worse than
swapping to the eMMC, but avoids …
> zram: Enable more aggressively

- eos-enable-zram
In testing we found that lz4 is not supported on ARM,
and since we did not see a significant peformance difference
between lzo and lz4 on Intel (and achieved a higher compression
ratio using lzo), and since most of our testing has been with lzo,
let's go with the default lzo at least for now.
https://phabricator.endlessm.com/T16228
> zram: switch from lz4 to default lzo

- eos-enable-zram
Performance is significantly degraded when swapping to spinning HDDs,
and zram offers much better performance.  For now, let's disable
the swap partition at boot for all users and use zram instead.
In the future, we may consider other options such as zswap to make
more effective use of disk swapping, or combining zram with swap
(if we can ensure that zram has the higher priority), or removing
the swap partition altogether.
https://phabricator.endlessm.com/T21726
> Disable disk swap and enable zram for all users

- nvidia/dmi-blacklist
The Acer Nitro N50-600 with GTX1060 fails to resume from S3 suspend
in approximately 1 of 5 boots.
When the hang is observed, the system remains responsive over ssh,
where you can login and see that Xorg is using 100% CPU.
Blacklist the buggy nvidia driver so that the nouveau driver is
used instead.
https://phabricator.endlessm.com/T21513
> nvidia: prevent loading on Acer Nitro N50-600

- Makefile.am
- eos-config-journal
- eos-config-journal.service
This is meant to allow us easier access to detailed logs by ensuring
they already exist by the time an issue has been discovered. This is
particularly important when users often change their behavior just after
enabling logging which can lead to reporting of unhelpful journals.
Specifically, we enable the persistent journal by creating
/var/log/journal if /var is on a non-{MMC,SD} device since those storage
types can be degraded with significant writing (though our configuration
rate-limits the journal's access to storage significantly).
https://phabricator.endlessm.com/T21771
> enable persistent journal on durable storage devices

- eos-update-flatpak-repos
When we started dynamically creating Flatpak remotes on upgrades using
flatpak remote-add in boot scripts, we uncovered a bug in ostree's remote
configuration that meant ostree was creating entries in /etc/ostree/remotes.d
but flatpak was directly editing /ostree/repo/config, meaning that the
remote was created twice. This was fixed around 3.3.0 by setting
add-remotes-config-dir to false in an init script. (this was T19077)
People who upgraded before this fix could still have broken entries in
remotes.d, so we forcibly remove these files and any config in the ostree
repo, and then allow the remotes to be dynamically re-added. The OS
(including this script, and more critically now the OS updater) relies on
these remotes being present for upgrades to take place. …
> eos-update-flatpak-repos: remove broken Flatpak remotes.d configuration

- eos-ostree-remotes-config
- eos-update-flatpak-repos
The previous fix for this wouldn't actually work in some cases since the flatpak installation can't even be opened if there are duplicate remote entries. This moves similar functionality to eos-ostree-remotes-config, which is setup to run before any other ostree or flatpak services. The work done there is done entirely with python's ConfigParser since ostree will refuse to open the repo when there are duplicate remote entries.
I tested this on my system and I think it should work well, but I didn't actually try it out on old images...
https://phabricator.endlessm.com/T22258
> Cleanup /etc/flatpak/remotes.d take 2

- eos-repartition-mbr
This package never had a dependency on python2; as a result, this script
broke when we removed the apparently-unused Python 2.7 from the OS.
In Python 2, sys.stdin.read() reads raw bytes. In Python 3, it reads
Unicode characters. Since we actually do want to read 8 raw bytes, we
read from the underlying raw stream at sys.stdin.buffer.
https://docs.python.org/3/library/sys.html#sys.stdin
https://phabricator.endlessm.com/T22665
> eos-repartition-mbr: invoke python3, not python (2)

- eos-config-journal
- eos-config-journal.service
This is as suggested by `man systemd-journal`:
> On systems where /var/log/journal/ does not exist yet but where
> persistent logging is desired (and the default journald.conf is used),
> it is sufficient to create the directory, and ensure it has the
> correct access modes and ownership:
mkdir -p /var/log/journal
systemd-tmpfiles --create --prefix /var/log/journal
Without this, `/var/log/journal` is owned by root:root, which prevents administrators (who are members of 'adm' but not of 'root') from being able to see privileged parts of the journal without `sudo`.
An alternative approach would be to order this job before `systemd-tmpfiles-setup.service`, but there's no particular need to block the boot process on creating this directory.
I also included a fix to skip this job on live …
> eos-config-journal: set correct permissions on /var/log/journal

- dracut/endless.conf
On recent ubuntu kernels, the ext4 filesystem is now built in.
Newer dracut versions will log an error if they don't find the
requested ext4 module to install in the initramfs.
dracut-install: ERROR: installing 'ext4'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.KDpSCO/initramfs -N nouveau --kerneldir /lib/modules/4.16.0-4-generic/ -m ext4 isofs
https://phabricator.endlessm.com/T22810
> dracut conf: drop ext4 filesystem module

- eos-firstboot.service
Service units of type oneshot delay the execution of follow-up units
until is main process exits. Since we always use ext4, the filesystem
extension can be performed on-line, so lets change this unit to simple
(the default when neither Type= nor BusName= are specified, but
ExecStart= is).
This avoids having eos-firstboot.service acting as bottleneck blocking
basic.target and the whole boot process as a consequence.
https://phabricator.endlessm.com/T22685
> eos-firstboot: Change service type to simple

- eos-repartition-mbr
Previously we would see the following warning on a successful run:
> eos-repartition-mbr: line 78: warning: command substitution: ignored null byte in input
This was because we read a full 512-byte sector at the start of where we
thought the GPT should be, and that sector would contain null bytes. But
we are only interested in 8 bytes which we expect to be the string "EFI
PART". We can avoid this warning by telling dd to read exactly 8 bytes.
> eos-repartition-mbr: read exactly 8 bytes of backup GPT

- debian/control
- eos-repartition-mbr
- tests/test_repartition_mbr.py
sfdisk now does this automatically, since https://github.com/karelzak/util-linux/commit/5635d19:
> always (except --wipe=never) wipe old partition tables
with the nuance that it only wipes the "EFI PART" bytes of the table, not the whole sector, which is fine. So:
* adjust the test accordingly
* drop our logic to try to do the same thing (which fails if sfdisk has this behaviour, because the EFI PART in the backup GPT is zeroed)
* add a versioned dependency on util-linux
I do not understand how https://phabricator.endlessm.com/T22665 worked when I QAed it since we have a new-enough sfdisk in eos3.4. We should backport this change for 3.4.2.
> eos-repartition-mbr: don't try to zero GPT headers

- dracut/repartition/endless-repartition.sh
- tests/test_repartition.py
Overall, we achieve better results with zram than with disk
swap partitions, so we are no longer going to create a swap
partition on first boot.
For existing installations, if we already created the swap partition,
we currently don't do anything to remove it, so for now we need to
continue to explicitly disable the swap partition when we enable zram.
In the future we may want to automatically remove such a partition
to reclaim disk space.
https://phabricator.endlessm.com/T21758
> endless-repartition: stop creating swap partitions

- eos-update-flatpak-repos
Previous versions of eos-update-flatpak-repos left behind local ostree refs to the old origin/branch of the apps it had migrated. This meant that once flatpak had upgraded the app and pulled the new ref from the network, the old one was never cleaned up, leaving behind the commit and disk space associated with the old version of the app.
To both fix this problem, and prevent it happening again, we build a list of matching ostree refs which should shadow the installed flatpaks we are migrating, and copy the ref to the new name if the app branch or origin is changed during the migration. The remaining refs in our list at the end of the process have either just been migrated, or were migrated in the past, and are therefore deleted.
https://phabricator.endlessm.com/T22763
> T22763: clear up / avoid old refs for flatpaks which have been migrated

- nvidia/dmi-board-blacklist
- nvidia/nvidia-graphics-setup
ASUS has changed the DMI naming policy.  The same computer model's
product name will be different according to different marketing area,
but the board's name will not.  This new policy starts from Coffee
Lake / Canon Lake / AMDRavenRidge / Whiskey Lake platforms.
This patch adds the new blacklist mechanism which checks the board.
https://phabricator.endlessm.com/T22896
https://phabricator.endlessm.com/T22813
Signed-off-by: Jian-Hong Pan <jian-hong@endlessm.com>
> nvidia: add board blacklist

- nvidia/dmi-blacklist
The NV GTX 1050 Ti of Predator Orion 5-100 cannot resume back from
suspend on first boot with the normal display when use the nvidia driver
(ver. 390.48).  If we ssh into the system, we can find that X takes the
CPU resource almost 100%.
So, change the driver to nouveau which can solve the problem.
https://phabricator.endlessm.com/T21605
Signed-off-by: Jian-Hong Pan <jian-hong@endlessm.com>
> dmi-blacklist: Acer Predator Orion 5-100 can't use nv drv

- eos-enable-zram
Swapped pages to zRAM occupies space in the physical RAM (in its compressed
state), so having a too big zRAM-backed swap partition can actually impact
performance in a negative way, since a big chunk of RAM would be used if
all swap is occupied. For instance, for a system with 2GB of RAM and 4GB
of zRAM with a typical compressed ratio between 3:1 and 4:1, this would
mean that as much as 1GB - 1.3GB of RAM could be used for zRAM, leaving
a bare amount of 700MB - 1GB left as uncompressed physical memory.
Based on some discussions found online with suggestions about how to setup
zRAM for ChromiumOS devices [1], and also on an actual configuration file
confirming such suggestions [2], I'm changing the configuration of zRAM
to match that policy of `zRAM_size = RAM_size * 1.5`, in an attempt to …
> Configure zRAM to be 150% of the physical RAM memory's size

- nvidia/nvidia-graphics-setup
On some hardware models (Dell XPS 15) this crashes the kernel, so
support blacklisting it.
https://phabricator.endlessm.com/T23272
> nvidia: support blacklisting nouveau module too

- nvidia/dmi-blacklist
There is no Endless logo shown during boot on Acer Nitro N50-100.
Blacklisting the nvidia driver and using nouveau fix this issue.
https://phabricator.endlessm.com/T23367
Signed-off-by: Jian-Hong Pan <jian-hong@endlessm.com>
> dmi-board-blacklist: No Endless logo shown during boot on Nitro N50-100

- eos-update-flatpak-repos
Due to a bug in eos-updater (T23385), upgrades from OS version 3.3 which
follow the checkpoint to move from the eos3 to the eos3a branch from
version 3.4 onwards do not remove the old eos:os/.../eos3 ref which
points to the last 3.3 release. This means that even after the 3.3 OS is
undeployed (after a second 3.4 update) the objects are kept around in
the OSTree repo - approx 3GB of wasted disk! Although we can fix the
updater bug for the next checkpoint, any system that has already
upgraded, and anyone else who uses the (still buggy) 3.3 updater to
follow the checkpoint, will have the leaked eos3 ref.
https://phabricator.endlessm.com/T23410
> eos-update-flatpak-repos: remove OSTree leaked refs for eos3

- nvidia/nvidia-graphics-setup
If modprobe.blacklist=nouveau is present on the kernel command line
nvidia-graphics-setup should not try to load the nouveau module.
https://phabricator.endlessm.com/T23272
> nvidia-graphics-setup: Respect modprobe.blacklist=nouveau

- eos-update-flatpak-repos
Arguably this should have been done in https://github.com/endlessm/eos-customer-support/blob/master/eos-upgrade-eos2-to-eos3.
The ec100 ref name is a guess.
https://phabricator.endlessm.com/T23443
> eos-update-flatpak-repos: remove eos2-related refs

- 50-laptop-keyboard-wakeup.rules
ASUS new laptop models UX333FA, UX444FN, UX533FD and Acer Swift
SF314-55G which are powered by Intel WiskyLake CPUs and supports
s2idle can not wake up the system by keypress. It's due to the EC
does not signal SCI event by keypress after s2idle. The EC code
seems to be applied to coming models with new Intel WiskyLake CPUs.
Needs more models to verify.
To minimize impact and unwanted wakeups, we support keyboard wakeup
on specific systems identified by DMI.
https://phabricator.endlessm.com/T23406
> Enable PS2 keyboard wakeup on specific laptop systems

- 50-disk-bfq.rules
- Makefile.am
- dracut/endless.conf
Set the scheduler to BFQ on block devices with a device type of disk, and add
the bfq module to the initrd so this udev rule works from early boot. This will
only impact SCSI devices on Endless systems, where we have switched the default
of the SCSI disk devices to the new MQ scheduler framework, which is a
pre-requisite of BFQ. Other block devices such as MMC which don't currently use
the MQ framework can't access BFQ, in which case this action is a no-op and the
current in-kernel default of CFQ remains.
https://phabricator.endlessm.com/T23725
> udev/dracut: enable BFQ by default on disk devices

- dracut/repartition/endless-repartition.sh
- eos-extra-resize
- eos-reclaim-swap
When running tests in OpenQA (which runs in QEMU), the disk uses the
virtio driver, whose devices are exposed as /dev/vd[a-z][0-9], rather
than /dev/sd[a-z][0-9].
Ensure that the disk repartitioning and resizing code handles these
device names. Critically, this ensures that the Endless partition is
resized to fill the virtual disk, rather than remaining about 6GB big
(which fills up rather fast and hence prevents any flatpaks from being
installed in OpenQA tests).
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T23739
> Support virtio disks as well as SCSI disks

- eos-update-flatpak-repos
Changes of origin don't change the deployed path on disk, and our
origin-changing code is idempotent, so we only need to check if something is
installed in the case the branch is being changed. If the ref we are migrating
to already exists, uninstall the old one.
https://phabricator.endlessm.com/T21141
> eos-update-flatpak-repos: check for and handle already-migrated apps

- .gitignore
- Makefile.am
- configure.ac
- psi-monitor/Makefile.am
- psi-monitor/psi-monitor.c
- psi-monitor/psi-monitor.service
Add a small service which will monitor pressure stall information (PSI)
from /proc/pressure and trigger the kernel's OOM killer when the system
enters a trashing state.
Since there is a chance the OOM killer may kill this service, it is set
to be restarted on failure by systemd.
https://phabricator.endlessm.com/T19943
>  Add Pressure Stall Information Monitor

- eos-update-flatpak-repos
Allows eos-update-flatpak-repos to rename Flatpak apps by re-implementing the previous manual branch manipulation in terms of re-committing the local ostree ref under a new name with the same contents, and amending the metadata so that Flatpak will re-deploy the new app successfully with NO_PULL.
On that baseline, app renaming is achieved by modifying the metadata and exported files of the app whilst the new commit is being built so that the exports are under the names permitted by Flatpak. The old app ID is recorded in the previous-ids metadata field in the deploy file, allowing https://github.com/endlessm/flatpak/pull/107 to take responsibility for renaming the app data folder at runtime.
Limitations include:
- no renaming for Extra Data apps
- no renaming of apps with extensions
- no …
> T23819: implement app renaming in eos-update-flatpak-repos

- eos-update-flatpak-repos
- tests/test_update_flatpak_repos.py
Our Flatpak is patched to propagate a previous-ids property from old
to new deploy file when deploying an app update, and to add all previous
IDs to the X-Flatpak-RenamedFrom key in the process.
However, in this script we only set previous-ids after deploying the
patched version of the app (under its new name). In any case, as far as
Flatpak is concerned, this is a wholly new app being installed, so there
would be no previous deployment to carry previous-ids forward from.
Since we are patching the .desktop files anyway while doing the
migration, we can just implement the same logic to update
X-Flatpak-RenamedFrom here, and add a test for this and other .desktop
file mangling.
I have not tested this on a real system, but in my defence I did write a test. …
> eos-update-flatpak-repos: update X-Flatpak-RenamedFrom

- .flake8
- Makefile.am
- debian/control
- eos-reclaim-swap
- eos-update-flatpak-repos
- tests/check-syntax
- tests/test_image_boot.py
- tests/test_live_boot_generator.py
- tests/test_reclaim_swap.py
- tests/test_repartition.py
- tests/test_repartition_mbr.py
I was reviewing https://github.com/endlessm/eos-boot-helper/pull/236 and found bugs just by running `flake8`, so let's automate that.
> Run flake8 during build

- eos-update-flatpak-repos
Attempt to get things to go faster - disable OSTree's fsyncs and leverage new _NO_TRIGGER API added to Flatpak in https://github.com/endlessm/flatpak/pull/124 to defer triggers until the end of the migration run.
Also fixes a bug found by @wjt where the flatpak-builder apps could not be migrated because they have an xa.metadata key on the commit, which no longer matched the /metadata file after our migrations were applied.
https://phabricator.endlessm.com/T23856
> T23819: optimisations/bugfixes for migration

- nvidia/nvidia-graphics-setup
To avoid screen tearing on Optimus systems, enable PRIME Sync
via the modeset module parameter.
https://devtalk.nvidia.com/default/topic/957814/linux/prime-and-prime-synchronization/
https://phabricator.endlessm.com/T24269
> nvidia: enable PRIME Sync

- eos-update-flatpak-repos
logging.basicConfig(), if called without any handlers (and with no
handlers previously configured), adds a logging.StreamHandler for stderr.
After calling it, we previously unconditionally configured a
JournalHandler to send log output to the systemd journal.
When run interactively, stderr isn't connected to the journal; but when
run for real after an upgrade, it is. This meant we logged everything to
the journal twice, making it rather hard to read. As it happens, the
prefix on each line was the same length, which helped a bit:
```
Oct 08 11:22:10 endless eos-update-flatpak-repos[332]: INFO:root:Found eos-apps:app/org.stellarium.Stellarium/x86_64/eos3 to migrate to flathub:app/org.stellarium.Stellarium/x86_64/stable
Oct 08 11:22:10 endless /usr/sbin/eos-update-flatpak-repos[332]: Found …
```
> eos-update-flatpak-repos: don't log twice to journal

- eos-reclaim-swap
For DOS partition tables, the msdos_partition_align() function called
in the disk.maximizePartition() codepath was modifying the partition
start, aligning it based on BIOS cylinder calculations. Drop that
constraint so that the sector will be unchanged.
This was causing the new partition to be written with a different start
sector (144585 instead of 131072), but here we are only trying to modify
the end. Add a sanity check to prevent that from happening again for
any reason.
https://phabricator.endlessm.com/T24454
> eos-reclaim-swap: avoid cylinder alignment for DOS partition tables

- eos-update-flatpak-repos
Add support to eos-update-flatpak-repos to migrate apps with extra data, so that we can migrate the Skype app to the Flathub version.
https://phabricator.endlessm.com/T24741
> T24741: support extra data and migrate Skype

- eos-config-journal
On a dual-boot eMMC system, `/dev/mapper/endless-image3` has SUBSYSTEMS=block. `lsblk` knows that its ancestor partition, eg `/dev/mmcblk0p3`, has SUBSYSTEMS=block:mmc:mmc_host:pci, but `lsblk DEVICE` shows information about DEVICE and its descendents, not its ancestors. Passing --inverse causes it to show the ancestors instead.
I don't have a dual-boot device easily accessible right now (and don't have a Windows computer with eMMC at all) so I've not actually tested this change in situ.
https://phabricator.endlessm.com/T25023
> eos-config-journal: detect MMC on dual-boot systems

- eos-update-flatpak-repos
- tests/test_update_flatpak_repos.py
fa409368c1ffbce4be40a3b79f449b71f9ae072d added support for migrating extra data apps, but broke migrating normal apps:
Failure applying migration to com.github.Slingshot
Traceback (most recent call last):
File "/usr/sbin/eos-update-flatpak-repos", line 1495, in _migrate_installed_flatpaks
**kwargs,
File "/usr/sbin/eos-update-flatpak-repos", line 1331, in copy_commit
metadata, vendor_prefixes = rewrite_app_id(repo, mtree, old_app_id, new_app_id)
File "/usr/sbin/eos-update-flatpak-repos", line 1235, in rewrite_app_id
if metadata.remove_group(FLATPAK_METADATA_GROUP_EXTRA_DATA):
GLib.GError: g-key-file-error-quark: Key file does not have group “Extra Data” (4)
This is because g_key_file_remove_group() returns FALSE with the GError set if the group is not present; this becomes an exception in …
> eos-update-flatpak-repos: fix migrating non-extra data apps

- fallback-fb-setup/fallback-fb-setup.service
Use the correct path for the service binary.
https://phabricator.endlessm.com/T24682
> fallback-fb-setup: Fix executable path in unit file

- factory-reset/eos-factory-reset-users.service
Use the correct path for the reset-users service binary.
https://phabricator.endlessm.com/T24613
> factory-reset: Fix executable path in unit file

- dracut/image-boot/module-setup.sh
With the new lvm2 version in debian buster, common dmsetup commands
seem to wait for udev rules to communicate completion. If this rules
file is not present, the "dmsetup create" hangs indefinitely.
https://phabricator.endlessm.com/T25331
> image-boot: install 95-dm-notify.rules

- dracut/image-boot/eos-image-boot-generator
55-dm.rules looks like it should take care of setting the DM_NAME
udev variable for device mapper devices. However, in our case, it is
not doing this. The flow is hard to analyze but I observed that it's
not setting the name, and is instead reaching the dm_disable section
where it asks udev to stop watching the device.
DM_NAME was being set anyway because 60-kpartx.rules used to trigger
and call dmsetup_env to set these variables, but as of the new
multipath-tools version, that no longer happens for this device.
Just read the device mapper name from /sys attributes directly,
avoiding dependence on 55-dm.rules which is not working as we would hope.
https://phabricator.endlessm.com/T25493
> eos-image-boot: read device mapper name from sysfs attributes

- 50-eos.preset
It fails to start due to the lack of a system-wide PulseAudio session:
pulse.c: pa_simple_new() failed: Connection refused
According to README.Debian, running a system-wide instance of this
daemon is not a recommended configuration, and debian/rules uses
"dh_systemd_enable --no-enable" to disable it by default on Debian
systems. Disable it here, too. (Previously, the package did not include
a .service file, and the init script checked an off-by-default flag in
/etc/default/speech-dispatcher.)
https://phabricator.endlessm.com/T25605
> eos-preset: disable speech-dispatcherd.service

- 50-eos.preset
We don't want to enable any unit from wpa_supplicant as we don't
configure interfaces individually outside of Network Manager. Network
Manager starts wpa_supplicant via D-Bus when needed.
This also times-out during boot, adding a 90s delay bacause it requires
sys-subsystem-net-devices-multi-user.device, which does not exist.
https://phabricator.endlessm.com/T25608
> eos-preset: Disable wpa_supplicant-wired@.service

- 50-eos.preset
We don't want to enable any unit from wpa_supplicant as we don't
configure interfaces individually outside of Network Manager. Network
Manager starts wpa_supplicant via D-Bus when needed.
This also times-out during boot, adding a 90s delay because it requires
sys-subsystem-net-devices-multi-user.device, which does not exist.
https://phabricator.endlessm.com/T25608
> eos-preset: Disable wpa_supplicant-nl80211@.service

- nvidia/dmi-blacklist
Tested with new nvidia driver 418.43 and Linux kernel 5.0.0+, which fix
the original suspend & resume issue on Acer Nitro N50-600 equipped with
NVIDIA GTX 1060.  Besides, we also need the new nvidia driver to be
loaded for the new NVIDIA cards like RTX 2070.  So, this patch removes
Acer Nitro N50-600 on the black list.
https://phabricator.endlessm.com/T25980
Fixes: commit 179baa7b5783 (nvidia: prevent loading on Acer Nitro N50-600)
> nvidia: unblacklist Acer Nitro N50-600

- 50-eos.preset
This is pulled in as a dependency of podman. crio(8) describes it as:
> OCI-based implementation of Kubernetes Container Runtime Interface Daemon
It fails to start at boot:
crio[465]: time="2019-03-28 23:35:29.396993833Z" level=fatal msg="no default routes found in "/proc/net/route" or "/proc/net/ipv6_route""
systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: crio.service: Failed with result 'exit-code'.
It succeeds if you start it later, so this is likely a dependency issue.
However, since we don't explicitly want it, let's just disable it.
https://phabricator.endlessm.com/T25542
> eos-preset: disable crio

- 50-eos.preset
This unit is harmless in and of itself, but it Wants=crio.service and is WantedBy=multi-user.target, meaning that the previous change to disable crio.service (6989c7b / #265) is ineffective.
https://phabricator.endlessm.com/T25542
> eos-preset: disable crio-shutdown, too

- 50-eos.preset
We don't want the family-safe default settings to be enabled unless the systemd
unit is explicitly enabled in the image builder.
https://phabricator.endlessm.com/T23464
> eos.preset: disable eos-safe-defaults unit by default

- eos-update-flatpak-repos
A speculative fix for the issue reported on
https://community.endlessos.com/t/update-fail-use-endless-os-3-3-19/8848.
This user has org.gnome.Platform//3.28 installed from the 'gnome'
remote, but does not have a 'gnome' remote, because the eos3.3 version
of this script forcibly deletes it.
https://phabricator.endlessm.com/T25809
> eos-update-flatpak-repos: migrate GNOME 3.28 runtime

- nvidia/dmi-blacklist
This reverts commit 56df1d3247b5e6182b7ea4dc2e0362ca918b4aa5.
This is believed to have been merged for nexthw support, on the
assumption that there would be no other EOS 3.5.x released. Turns out we
need an emergency release for Endless Hack, so I'm reverting this change
to avoid a regression of T21513.
https://phabricator.endlessm.com/T26629
> Revert "nvidia: unblacklist Acer Nitro N50-600"

- eos-update-flatpak-repos
- tests/test_update_flatpak_repos.py
047f46b introduced the idea of unconditionally rewriting the metadata in the case that the app being migrated is an extra data app, previously only done when the app ID was changing. Unfortunately this exposed a bug in the rewriting of exports which causes the file handling to fail when the new and old ID are the same. Avoid entering this code path if the app IDs are the same, and add a test case to ensure that the desired behaviour is achieved. (Manual testing with the relevant hunk removed from the patch shows that the new test did indeed fail without this change.)
https://phabricator.endlessm.com/T26588
>  eos-update-flatpak-repos: avoid rewriting exports un-necessarily

- eos-update-flatpak-repos
In the case we are migrating an extra data app without renaming it, we have to
rewrite the metadata to strip the extra data section, but these other changes
are redundant.
https://phabricator.endlessm.com/T26588
>  eos-update-flatpak-repos: avoid un-necessary metadata changes

- eos-update-flatpak-repos
https://phabricator.endlessm.com/T27078
> eos-update-flatpak-repos: Migrate BillardGL from eos-apps to flathub

- dracut/repartition/endless-repartition.sh
When booting with systemd-boot and auto mounting the ESP, the service
file to fsck the root fs ends up in generator.late instead of
generator, leading to a failure on the first boot after install.
Look in both places to increase chances of success.
https://phabricator.endlessm.com/T27041
> endless-repartition: Check for root fsck service in generator.late too

- eos-live-boot-overlayfs-setup
The approach attempted in commit 4d348fb9b56ff34cf150d68a6012b6ce5778d51a
didn't work because the parent mount at /run is a shared mount, and
mount --move cannot be used there.
There isn't an existing clear place in the hierarchy where we can work
with private mounts instead, so just change the approach, instead
populating the overlayfs upperdir in advance.
This will need tweaking when we implement support for persistent overlayfs
storage (and that's also true for other code in this file).
https://phabricator.endlessm.com/T27158
> image-boot: alternative method for seeding machine-id in overlay

- dracut/repartition/endless-repartition.sh
- dracut/repartition/module-setup.sh
systemd-boot passes us the ESP's UUID in an EFI variable, and
systemd will only mount the ESP if the UUID on disk matches the one
systemd-boot passed.
When we repartition all the UUIDs change, so update the variable
to match so the first boot properly mounts the ESP.
https://phabricator.endlessm.com/T27041
> endless-repartition: Fix up ESP UUID EFI variable for PAYG

- dracut/repartition/endless-repartition.sh
UUIDs are hex numbers, and when they start with a decimal digit, eg 1
the printf becomes: printf \06\001
that's 0x06 0x01 which is not at all the intended 0x06 0x00 0x31
Switch all the octal to 3 digit (as an aside, the shell used doesn't
support hex notation, which is why we're using octal)
https://phabricator.endlessm.com/T27041
> endless-repartition: Fix up ESP UUID EFI variable for PAYG again

- dracut/repartition/endless-repartition.sh
- dracut/repartition/module-setup.sh
Overwriting the LoaderDevicePart variable doesn't work on all EFI
firmware implementations. Some (including tianocore, where this
behaviour can be verified by inspection in Variable.c) don't allow
volatile variables to be altered in any way at run time.
It works on VirtualBox, where I've been testing this code, but not
on any of the physical hardware I've tried on.
Instead of writing downstream hacks into systemd to make this work,
bind mount our chosen variable contents over the file we can't change.
This leaves a harmless bind mount lying around on the first boot -
this can be seen in 'df' output.
https://phabricator.endlessm.com/T27041
> endless-repartition: Update loader efi var so it works on real computers

- 50-eos.preset
smartmontools was added for some hardware tests from Checkbox, and does
not need to be running in the OS. It currently fails to start on OpenQA
and eMMC-only devices with the following error:
smartd[1958]: DEVICESCAN failed: glob(3) aborted matching pattern /dev/discs/disc*
smartd[1958]: In the system's table of devices NO devices found to scan
https://phabricator.endlessm.com/T27837
> eos-preset: Disable smartd.service

- eos-live-boot-overlayfs-setup
On ISO-USB boots, an extra partition will now be created during early
boot.
Once we reach the point of overlayfs setup, attempt to locate this
partition.
If it is unformatted (still has the marker), format it as ext4.
Then mount it and use it as persistent backing storage for the
overlayfses.
https://phabricator.endlessm.com/T27771
> live-boot: format and use persistent storage partition

- Makefile.am
- hack-remove-global-override.service
Old hack computer has a global flatpak override file. In the new hack
experience we're going from using a custom product EOS to use the main
EOS branch so, we need to remove this global override and we'll use
local override for each application.
This patch adds a service that will remove the global override, only for
old hack-computer users, it checks for the HackComponents flatpak that
should only be installed in old hack computers, and if that exists it'll
remove the global override.
This service is based on the eos-update-flatpak-repos to be run only on
update.
https://phabricator.endlessm.com/T27984
1. Place the systemd service in your system:
```
cp hack-remove-global-override.service /etc/systemd/system
```
2. You should need to have `com.endlessm.HackComponents`
3. Create the …
> hack: Add new service to remove the global override

- eos-update-flatpak-repos.service
Installing a Flatpak now involves talking to accountsservice, even if
running as root. Without this change, the script job fails with:
ERROR:root:Failure applying migration to org.squeakland.Etoys
Traceback (most recent call last):
File "/usr/sbin/eos-update-flatpak-repos", line 1589, in _migrate_installed_flatpaks
arch, new_branch)
gi.repository.GLib.GError: g-io-error-quark: Could not connect: No such file or directory (1)
https://phabricator.endlessm.com/T28386
> eos-update-flatpak-repos: skip parental controls checks

- eos-update-flatpak-repos
A speculative fix for the issue reported on
https://community.endlessos.com/t/no-se-ejecuta-steam-desde-hace-tiempo/10758.
This user has org.gnome.Platform//3.22 installed from the 'gnome'
remote, but does not have a 'gnome' remote, because the eos3.3 version
of this script forcibly deletes it.
https://phabricator.endlessm.com/T25809
> eos-update-flatpak-repos: migrate GNOME 3.22 runtime

- eos-update-flatpak-repos
The now-retired "gnome" flatpak remote served org.gnome.Platform//3.20
and org.freedesktop.Platform//1.4, so there's some chance these exist on
some user's system, and are preventing that user from updating due to
https://phabricator.endlessm.com/T25809. So migrate them both to
Flathub. Flathub does not in fact serve those runtimes any more (or
ever?) but as long as they're not deployed from a remote that doesn't
exist, the update to 3.3.20 (yet to be released) and beyond should
succeed.
https://phabricator.endlessm.com/T25809
> eos-update-flatpak-repos: Migrate GNOME 3.20 and fd.o 1.4

- eos-update-flatpak-repos
During the 3.7.6 release I made a poorly thought through decision to
override the image builder URLs so that they pulled directly from our
server instead of our CDN that kept failing. I thought that the URLs
would only be used while pulling the data and not end up as the final
URLs. That was not the case.
Add a function to walk through all the OSTree and Flatpak remotes and
swap our internal ostree.endlessm-sf.com domain for the CDN
ostree.endlessm.com domains.
I didn't test this at all yet but wanted to get it out for review.
https://phabricator.endlessm.com/T29535
> eos-update-flatpak-repos: Fix remote URL snafu

- Makefile.am
- dracut/image-boot/eos-map-image-file
- eos-image-boot-dm-setup.service
- eos-live-boot-overlayfs-setup
Let endless use a large file created by the installer on the exfat partition for persistent storage.
> Allow persistent storage for combo usb sticks

- eos-live-boot-overlayfs-setup
I made the false assumption that dist_libexec_SCRIPTS installed
into /usr/libexec, but I didn't create packages to adequately
confirm installation location.  The actual location on an eos
system is /usr/lib/eos-boot-helper
Fix the script to look in the right place.
https://phabricator.endlessm.com/T14891
> eos-live-boot-overlayfs-setup: Fix eos-map-image-file invocation

- dracut/image-boot/module-setup.sh
We use the device mapper in our dual boot configurations to map the file
on the user's windows partition as a block device that hosts endless.
Recently something broke in these configurations, and now systemd tries
to unmount our /var partition at boot. It appears that this may have
been a problem waiting to manifest for some time, because under 3.7.8
we see evidence of systemd wanting to unmount /var but bailing on the
process due to other conflicts.
The problem is that on the transition from initrd to real root we
have to clean the udev db to remove anything that was created with
the initrd's set of udev rules - which may differ from the booted
system's udev rules.
Once the db is cleared, udevadm trigger is used to introduce all
the devices to the booted system's ruleset.
However, …
> dracut: Add the device mapper module to our config

- eos-image-boot-dm-setup
- eos-image-boot-dm-setup.service
Combo install sticks made by our windows install tool lost the ability to install endless recently
due to mistakes in the new persistent storage code.
Fix those mistakes and restore the install functionality.
https://phabricator.endlessm.com/T30318
> Fix installer when run from winstaller "combo" sticks

- eos-migrate-firefox-profile
- tests/test_migrate_firefox_profile.py
Strictly speaking we should have done this for all the other
applications that we have migrated. However, the browser is more
noticeable, since there is always at least one other, higher-priority
browser installed.
https://phabricator.endlessm.com/T29746
> firefox: Update MIME type associations

- Makefile.am
- eoslive-kolibrihome-setup.service
- run-kiwixhome.mount
- run-kolibrihome.mount
- run-media-eoslive.mount
- tmpfiles.d/flatpak-extension-kiwix-usb-content.conf
- tmpfiles.d/flatpak-overrides.conf
Ship a mount unit to always mount /dev/mapper/endless-image-device on live USB systems. This is a device-mapper device which maps the 'eoslive' partition minus the image file that the system boots from.
If there is Kolibri content available in it, make it available for the Kolibri app in EOS.
This also incidentally fixes a bug on live+installer combo USBs when launching the installer from the FBE, backing off, then trying to launch it from the user session.
https://phabricator.endlessm.com/T22735
https://phabricator.endlessm.com/T30599
> live: Make kolibri data from eoslive available in EOS

- eos-live-boot-generator
https://phabricator.endlessm.com/T30828
> eos-live-boot-generator: Rename .kolibri to KOLIBRI_DATA

- 50-eos-user.preset
- Makefile.am
- configure.ac
The pipewire service can still be activated manually or via socket activation.
https://phabricator.endlessm.com/T30785
> eos-user-preset: Add user presets to disable pipewire service

- dracut/image-boot/eos-image-boot-setup
We recently started using the dracut busybox module, and this has
replaced util-linux mount with busybox's implementation of mount.
For some reason busybox isn't figuring out what fs type our .iso
files are when the isofs kernel module isn't already loaded.
Specify it manually when mounting to work around this problem.
https://phabricator.endlessm.com/T30937
> image-boot-setup: Workaround busybox issue by manually specifying fs

- dracut/image-boot/eos-image-boot-setup
Busybox losetup does not have --show. Its -f will show the next
available loop device, or, if you pass an image file, it will use (but
not show) the next available loop device.
https://phabricator.endlessm.com/T30937
> eos-image-boot-setup: Fix calls to busybox's losetup

- dracut/image-boot/eos-image-boot-setup
We're accidentally clearing the image_device variable when we
need its content later.
https://phabricator.endlessm.com/T30937
> eos-image-boot-setup: Don't clear image_device variable

- dracut/endless.conf
Dracut parses config files by executing them in the shell, so config
lines that add to variables are required to have spaces inside the
strings they add, or options can get crushed together.
Our config has always been "wrong", but didn't generate a warning until
we upgraded to a more recent version of dracut. It also doesn't fail
because we only have the one instance of add_drivers+=
Fix the warning by adding protective spaces to the string.
https://phabricator.endlessm.com/T31021
> dracut: Add protective spaces for shell variable concatenation

- eos-update-flatpak-repos
A user on the forum hit this error:
```
INFO:root:Found gnome:runtime/org.gnome.Platform/x86_64/3.28 to migrate to flathub:runtime/org.gnome.Platform/x86_64/3.28
ERROR:root:Failure applying migration to org.gnome.Platform
Traceback (most recent call last):
File "/sysroot/home/irena/eos-update-flatpak-repos", line 1698, in _migrate_installed_flatpaks
migrate_extra = is_extra_data(repo, ostree_refs[old_ostree_ref])
KeyError: 'gnome:runtime/org.gnome.Platform/x86_64/3.28'
```
So, make the code a bit more robust so that it doesn't error out when
the old ref doesn't exist and we can still migrate the deploy file.
We had already encoded the assumption that the old ref might not exist
with the check "if old_ostree_ref in ostree_refs and not new_ref:", so
this just makes it so we don't error out …
> eos-update-flatpak-repos: Fix a missing ref edge case

- eos-update-flatpak-repos
We retire the Hack flatpaks in the eos-apps repository and use the Flathub one instead.
https://phabricator.endlessm.com/T31133
> eos-update-flatpak-repos: migrate Hack apps

- Makefile.am
- configure.ac
- eos-migrate-chromium-profile
- eos-migrate-chromium-profile.service
- tests/Makefile.am
- tests/test_migrate_chromium_profile.py
- tmpfiles.d/chromium-system-services.conf.in
General notes on migration:
- `$config_dir/Default/Preferences` have a few mentions to `/usr/lib/chromium-browser/resources/` which doesn't even exist in the current version. The values are not updated during migration.
- Some services credentials (e.g. gmail) are lost during migration (requiring re-login)
- Some log files have entries referring to `~/.config/chromium`. This is ignored and log files are unchanged as they may be useful in case we need to differ logs from old and new version
- The migration always runs if `~/.var/app/org.chromium.Chromium/.migrated` (created at the end of the migration) doesn't exist, even if `~/.var/app/org.chromium.Chromium` does:
- This is such that we can update `~/.config/mimeapps.list` to point the new chromium in case the old chromium is specified as …
> Migrate Chromium to Flathub

- tmpfiles.d/chromium-system-services.conf.in
This directory used to be created by the chromium-browser system package (which is no longer present) and is used when setting up the `org.chromium.Chromium.Policy.system-policies` flatpak extension. The lack of this directory breaks the extension and in turn the chromium flatpak fails to startup. Let's fix it by ensuring the dir exists when setting up the extension.
https://phabricator.endlessm.com/T30997
> tmpfiles: Ensure /etc/chromium-browser exists before attempting to create a symlink to it

- eos-update-flatpak-repos
Without this change, having matched `runtime/com.hack_computer.Clubhouse.Locale/x86_64/eos3`, the script would try and fail to uninstall `app/com.hack_computer.Clubhouse.Locale/x86_64/eos3`.
Unfortunately the error was masked by c262b983eaf649b91bdb0c9a25d2d3214bee4ea2.
Add a warning in the previously silently-failing case, and fix the logic error that caused the wrong thing to be uninstalled.
https://phabricator.endlessm.com/T31185
> eos-update-flatpak-repos: Use the correct kind for app extensions

- eos-image-boot-dm-setup.service
This reverts commit 9589ea4ae7df358f4994ab308080060a90db46c8.
This condition is preventing eos-image-boot-dm-setup.service from
getting started on some setups with the Endless Key, in which case the
persistent storage file never gets mapped.
https://phabricator.endlessm.com/T30376
> Revert "eos-image-boot-dm-setup: Don't start if the dm file already exists"

- eos-update-flatpak-repos
This adds an workaround to fix an issue when migrating `com.hack_computer_Clubhouse.Locale` from `eos-apps` to `flathub`. The current migration fails when attempting to update the runtime when partially installed (e.g. only has a subset of the available
directories, corresponding to the locales on the system). To work around that we make sure to uninstall the old (from `eos-apps`) runtime before attempting the migration.
That has the side effect that the new `.Locale` won't get installed until the app (Clubhouse) gets updated next (either via automatic updates or manually) or if the user manually installs it.
Given the `.Locale` runtime is not mandatory the app should still work fine.
https://phabricator.endlessm.com/T31185
> eos-update-flatpak-repos: Workaround to fix issue migrating com.hack_computer_Clubhouse.Locale

- eos-image-boot-dm-setup
- eos-image-boot-dm-setup.service
We have seen eos-image-boot-dm-setup.service being launched twice by systemd for some reason that is not clear, but adding
RemainAfterExit=yes to the unit file prevents that from happening.
Also, the error checking logic there relies on only one thing being done in each branch of the case statement, since it looks at the return value from the last commant ($?), so this PR also moves the dumpexfat of persistent.img out of the case statement, so the error checking works as designed.
https://phabricator.endlessm.com/T30376
> eos-image-boot-dm-setup: Set RemainAfterExit=yes and fix error checking logic

- eos-live-boot-overlayfs-setup
If eos-image-boot-dm-setup.service has already run when this script
runs, blkid will return two devices matching the token passed via
endless.image.device, the real partition and the dm-device created by
eos-image-boot-dm-setup.
Limiting the output of blkid to one device only fixes a problem with the
logic in eos-live-boot-overlayfs-setup that was preventing
persistent.img from getting mapped when that happened, since it expects
only one device to be output.
https://phabricator.endlessm.com/T31223
> eos-live-boot-overlayfs-setup: Limit blkid output to one device

- eos-migrate-chromium-profile
- tests/test_migrate_chromium_profile.py
os.listdir() raises FileNotFoundError if the given directory doesn't
exist. Previously, eos-migrate-chromium-profile would crash in this
case, such as for every new user profile:
Traceback (most recent call last):
File "/usr/lib/eos-boot-helper/eos-migrate-chromium-profile", line 150, in <module>
main()
File "/usr/lib/eos-boot-helper/eos-migrate-chromium-profile", line 132, in main
update_desktop_shortcuts()
File "/usr/lib/eos-boot-helper/eos-migrate-chromium-profile", line 110, in update_desktop_shortcuts
for filename in os.listdir(DESKTOP_SHORTCUTS_DIR):
FileNotFoundError: [Errno 2] No such file or directory: '/sysroot/home/erikos/.local/share/applications'
In the case where the user had an old Chromium profile at
~/.config/chromium but no ~/.local/share/applications, this would mean …
> chromium: Don't crash if .local/share/applications doesn't exist

- eos-live-boot-generator
This patch adds the PYTHONPATH env to the kolibri flatpak override so it
can find custom extensions installed in the KOLIBRI_HOME.
https://phabricator.endlessm.com/T31369
> eos-live-boot-generator: override PYTHONPATH in kolibri

- debian/control
This dep is not used by anything on eos-boot-helper.
https://phabricator.endlessm.com/T31519
> Remove xterm dependency

- 50-eos.preset
This service is shipped by containernetworking-plugins and does not need to be running in the OS. It also provides a .socket unit
which should auto-activate it if/when needed.
> eos-preset: Disable cni-dhcp.service

- Makefile.am
- configure.ac
- flatpak-extension-runtime-fdo-openh264-ldconfig.service
- flatpak-extension-runtime-fdo-openh264-watcher.path.in
- flatpak-extension-runtime-fdo-openh264-watcher.service
- ld.so.conf.d/flatpak-extension-runtime-fdo-openh264.conf
- tests/test_reclaim_swap.py
- tmpfiles.d/flatpak-extension-runtime-fdo-openh264.conf.in
This change adds a tmpfiles.d config to link the openh264 flatpak runtime at /run/lib/openh264, a ld.so.conf.d config to make this dir available in the library search path and systemd units to re-run ldconfig when the runtime is installed/uninstalled in order to make it to the ldconfig cache.
We use a watcher service in order to re-run ldconfig (restart the unit responsible to run it) as path units can only start other units, not restart them.
https://phabricator.endlessm.com/T23316
> Add plumbing to add openh264 flatpak runtime to library search path when available

- psi-monitor/psi-monitor.c
Note that the value of `/proc/sys/kernel/sysrq` influences only the invocation via a keyboard. Invocation of any operation via `/proc/sysrq-trigger` is always allowed (by a user with admin privileges). [1] 
Changing the value in `/proc/sys/kernel/sysrq` is not necessary. So, we can safely remove `sysrq_enable_oom()`.
1. https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html#how-do-i-enable-the-magic-sysrq-key
> Remove sysrq_enable_oom()

- eos-update-flatpak-repos
These two apps were not previously migrated because they are both superseded by the same app, and we had wanted to make `org.gnome.Aisleriot.desktop` contain both in `X-Flatpak-RenamedFrom`.
I don't think this actually matters in practice, though. It will have the first one immediately, and then after being upgraded to the real Flathub version it will have both.
I also fixed a regression caused by a Flatpak becoming stricter, which broke the migration of at least 4 other apps.
https://phabricator.endlessm.com/T23936
> Migrate Freecell and Solitaire to Aisleriot, and fix a few other migrations

- eos-split-flatpak-repo
- tests/test_split_flatpak_repo.py
It's unusual but not unexpected to have refs leftover from a remote that
was deleted. Previously an error was raised, but now the tool does it's
best to figure out if it was a flatpak or OS ref. If it can't be figured
out, the ref will stay in both repos.
https://phabricator.endlessm.com/T32002
> eos-split-flatpak-repo: Handle refs from deleted remotes

- eos-split-flatpak-repo
- tests/test_split_flatpak_repo.py
Wire up the OSTree repo locking now that the API is available. That immediately deadlocked because the `.lock` file was being hardlinked to the new repo, so the hardlinking is reduced to just the objects and (likely nonexistent) deltas. Everything else is copied.
https://phabricator.endlessm.com/T32090
> Use repo locking when splitting flatpak repo

- Makefile.am
- eos-prune-printers
- eos-prune-printers.service
EOS 4 will change printer mechanism to driverless. So, there will be
transition action when users' computer upgrade from eos3a to eos4.
Add eos-prune-printers.servive to prune the installed printers and
drivers.
https://phabricator.endlessm.com/T31862
> eos-prune-printers: Add a service to prune printers

- eos-prune-printers
- eos-prune-printers.service
1. Fix the conflicted cups.service requirement by removing it. Because,
the script needs to stop it temporarily.
2. Sync the service's condition guard stamp filename with the script's.
3. Check the directories exist before remove them and their content.
https://phabricator.endlessm.com/T31862
> eos-prune-printers: Fix the service's condition & requirements

- eos-live-boot-overlayfs-setup
- eos-test-mode
Except for an EOS 3 upgrade gone wrong, the system flatpak repo should now be split from the system ostree repo. In that case we don't need any special handling for that configuration. Remove that and fix some other minor bugs while here.
I tested this in an installed VM and it worked correctly, but I haven't tested the live boot setup yet.
https://phabricator.endlessm.com/T32011
> Remove merged flatpak/ostree repo overlay setup

- 50-eos.preset
We are switching from ntp to the simpler systemd-timesyncd.
https://phabricator.endlessm.com/T16376
> eos-preset: Do not disable systemd-timesyncd

- 50-eos.preset
- Makefile.am
- eos-vm-generator
We need to enable virtualbox-guest-utils dynamically via a generator,
since ConditionVirtualization=oracle on the unit is not enought because
it will prevent conflicted units (systemd-timesyncd.service) from
starting.
https://phabricator.endlessm.com/T32330
> eos-vm-generator: Enable virtualbox-guest-utils via generator

- 50-eos.preset
Disable checkbox-ng.service by default. This avoids running on normal
users' system, which might be used as backdoor.
https://phabricator.endlessm.com/T32197
> eos-preset: Disable checkbox-ng by default

- eos-transient-setup
Since T32407, we use Chromium as the default browser in all images, so
there should be no images where booting in live mode could cause Chrome
to be downloaded unnecessarily (if it hadn’t already been downloaded by
another user).
Accordingly, we can drop the transient setup steps which prevent Chrome
from being auto-downloaded, and set Chromium as the default browser and
place it in the icon grid instead of Chrome.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
https://phabricator.endlessm.com/T32408
> eos-transient-setup: Drop support for replacing Chrome with Chromium

- eos-transient-setup
- eos-transient-setup.service
This script has many vestiges of a time when demo mode existed, but that time is long behind us. Remove the dead code and command-line option. Spotted while reviewing #354.
Then while I was here I decided to run `pylint` over the file and fix most of the warnings. We are left with:
```
************* Module eos-transient-setup
eos-transient-setup:1:0: C0103: Module name "eos-transient-setup" doesn't conform to snake_case naming style (invalid-name)
eos-transient-setup:1:0: C0114: Missing module docstring (missing-module-docstring)
eos-transient-setup:59:0: C0115: Missing class docstring (missing-class-docstring)
eos-transient-setup:161:15: W0703: Catching too general exception Exception (broad-except)
```
Legit (except the first one) but ones for another day.
I haven't tested it "for real" …
> Remove dead code from eos-transient-setup

- 50-eos.preset
This reverts commit e37cd5d85d2ee38c63838137fc8d218fde564e21.
Systemd-sysusers is a static unit. Disabling it does not disable others
invoking it. So, revert the commit.
https://phabricator.endlessm.com/T31589
> Revert "eos-preset: Disable systemd-sysusers by default"

- 50-eos.preset
This service updates any root-owned containers which have been manually
tagged to be automatically updated. This is not needed by a typical
Endless OS user.
https://phabricator.endlessm.com/T32795
> preset: Disable unwanted podman service & timer

- eos-split-flatpak-repo.service
Since `eos-update-flatpak-repos.service` and
`eos-updater-flatpak-installer.service` block boot via
`systemd-update-done.service`, ordering before them means that
`eos-split-flatpak-repos.service` blocks boot for a potentially very
long time.
Instead, order after those services and before any others that open the
system OSTree repo or the system Flatpak installation. By also reverting
to `DefaultDependencies=yes`, this service can run in the background
while the desktop is up. Of course, any system OSTree or Flatpak
operations will fail, but the system is otherwise usable.
This also allows the metrics to work since otherwise the service runs
befor the system DBus socket exists.
https://phabricator.endlessm.com/T32768
> split-flatpak-repo: Run service in background

- eos-split-flatpak-repo
- tests/test_split_flatpak_repo.py
The flatpak repo splitting has been really slow for many people, so record some statistics and send them in a new metric. Suggestions on the event name welcome.
https://phabricator.endlessm.com/T32790
> Add stats metric for splitting flatpak repo

- eos-split-flatpak-repo.service
Now that the service is running in the background, it would be better to
lower the IO priority so that the user gets to the desktop faster. Even
though they'll be blocked from using OSTree and Flatpak longer, being
able to see the desktop and use parts of it is a better indication that
the computer isn't broken.
https://phabricator.endlessm.com/T32768
> split-flatpak-repo: Use idle IO scheduling class

- tmpfiles.d/chromium-system-services.conf.in
- tmpfiles.d/flatpak-extension-kiwix-usb-content.conf
- tmpfiles.d/flatpak-overrides.conf
Per tmpfiles.d(5), the `D` directive empties the contents of the
directory when `systemd-tmpfiles` is run with `--remove`. This happens
on every boot from `systemd-tmpfiles-setup.service`, so all of these
directories were being emptied during boot. In many cases that's
probably harmless, but for `/etc/chromium-browser`, it deletes all
chromium system configuration.
https://phabricator.endlessm.com/T32863
> tmpfiles: Don't empty directories

- Makefile.am
- eos-ostree-bootloader-setup
- eos-ostree-bootloader-setup.service
Instead of relying on ostree's automatic bootloader detection, we'd like to specify it since we have to carry an ugly downstream patch to make the automatic detection do what we want. The configuration is simple since the bootloader is either u-boot or grub. In the grub case we want the ostree bootloader configuration to be `none` so that it only updates the bootloader spec entries and doesn't try to manage `grub.cfg`. After a checkpoint we can drop this script and unit.
https://phabricator.endlessm.com/T33364
> Add service to set ostree bootloader on existing systems

- dracut/endless.conf
In our tests, zstd reduces our initrd size by ~25% (16MB) and reduces the decompression time by ~17% (1.5s).
https://phabricator.endlessm.com/T33801
> dracut: Compress initrd with zstd

- flatpak-extension-runtime-fdo-openh264-watcher.path.in
- tmpfiles.d/flatpak-extension-runtime-fdo-openh264.conf.in
org.freedesktop.Platform//22.08 introduced this new branch for the 2.2.0 version of OpenH264. We already have the corresponding updates for libnoopenh264 in the OS.
As a bonus, this new version is also available for aarch64.
https://phabricator.endlessm.com/T30986
https://phabricator.endlessm.com/T33476
> Update openh264 extension version

- .gitignore
- Makefile.am
- configure.ac
- psi-monitor/Makefile.am
- psi-monitor/psi-monitor.c
- psi-monitor/psi-monitor.service
This reverts commit 356f7bb9f98feec80dbc158c36876661789ca88d.
We had replaced our in-house psi-monitor with low-memory-monitor in enforcing mode, but it has proved too aggressive to work in production, so we are reverting back to psi-monitor for now.
We'll try to understand why low-memory-monitor is behaving differently than psi-monitor despite using the same PSI levels, and hopefully switch back to low-memory-monitor again after some fine-tuning.
https://phabricator.endlessm.com/T34267
> Revert "psi-monitor: Drop Pressure Stall Information Monitor"

- Makefile.am
- debian/control
- eos-update-system-ca.service
Users, or Endless may add some CAs which do not belong debian packages. Those CAs will be updated into /etc/ssl/certs/ca-certificates.crt and would be likely to be mismatched from the shipped version in /usr/etc.
Add a helper service that runs update-ca-certificates after update and boot to sync up when it is needed.
https://phabricator.endlessm.com/T34308
> Update system CA store when /etc is updated

- Makefile.am
- debian/control
- eos-update-system-ca.service
Users, or Endless may add some CAs which do not belong debian packages. Those CAs will be updated into /etc/ssl/certs/ca-certificates.crt and would be likely to be mismatched from the shipped version in /usr/etc.
Add a helper service that runs update-ca-certificates after update and boot to sync up when it is needed.
https://phabricator.endlessm.com/T34308
(cherry picked from commit bb8e30b40a581443da7065cdfcf0804428fc5838)
There was a minor conflict in `Makefile.am` due to 4c9c7f305cf289a858e5387bd6febf222c6fff28 on master/eos5.0.
> Update ca certificates after upgrade (eos4.0 backport)

- eos-update-flatpak-repos
Historically the legacy runtimes were committed to the OS repo because they were built from the same packages and therefore were entirely deduplicated on the server. Fast forward many years and now the mixture of ostree and flatpak commits is starting to cause problems as flatpak is managing the repo metadata differently than flatpak.
The legacy runtimes have been duplicated into a new eos-runtimes repo that will contain only flatpaks. In order to use it, we need to migrate users to the new URL.
https://phabricator.endlessm.com/T33445
> eos-update-flatpak-repos: Migrate eos-runtimes to new URL

- eos-update-flatpak-repos
Historically the legacy runtimes were committed to the OS repo because they were built from the same packages and therefore were entirely deduplicated on the server. Fast forward many years and now the mixture of ostree and flatpak commits is starting to cause problems as flatpak is managing the repo metadata differently than flatpak.
The legacy runtimes have been duplicated into a new eos-runtimes repo that will contain only flatpaks. In order to use it, we need to migrate users to the new URL.
https://phabricator.endlessm.com/T33445
(cherry picked from commit 84ef840628f1bf56452b98fc86c263bda2d5fbd0)
> Backport "eos-update-flatpak-repos: Migrate eos-runtimes to new URL" to eos4.0

- dracut/endless.conf
As an Linux distribution, Endless OS tries to support as much machines as possible. So, install more modules into initramfs generated by dracut to support more storage/block devices during the boot time by disabling "hostonly".
If anyone needs to generate a host specific initramfs, they can pass the "--hostonly" option to dracut.
https://phabricator.endlessm.com/T34575
> dracut: Disable hostonly to install more modules into initramfs

- dracut/endless.conf
Don't include simpledrm in the initramfs to avoid the frame buffer transition on some platforms, like RPi 4B, which blocks system during plymouth execution.
https://phabricator.endlessm.com/T34648
> dracut: Omit simpledrm in initramfs

- tmpfiles.d/chromium-system-services.conf.in
We are removing AdBlock Plus, which is the last thing in
/usr/share/chromium. As a result, that directory will not exist.
If the broken symlink is left in place, bwrap is sad and Chromium fails
to start:
Apr 18 20:23:04 camille org.chromium.Chromium.flextop.chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default.desktop[3649]: bwrap: Can't find source path /var/lib/flatpak/extension/org.chromium.Chromium.Extension.system-extensions/x86_64/1: No such file or directory
Remove the tmpfiles rules that add that symlink.
https://phabricator.endlessm.com/T34534
> tmpfiles: Don't create Chromium system extensions symlink

- dracut/image-boot/eos-image-boot-setup
It has been a rough ride to accurately translate the endless.image.device=UUID=foo parameter into (e.g.) /dev/sda1, because udev was presenting sda and sda3 (if unformatted) with the same UUID.
We settled on a blkid behaviour that got us the right answer, but it no longer works after upgrading to Debian bookworm. blkid doesn't seem to register UUIDs for any of those devices now.
However, the udev situation has now improved, and an unformatted partition will no longer inherit filesystem info from the parent device: https://github.com/systemd/systemd/issues/14408
This means that we can give the by-uuid symlink approach another shot. Both sda and sda1 will contend for this symlink, but it seems fair to assume that the partition (which we want) will always be probed after the parent device. …
> eos-image-boot-setup: use by-uuid symlink for host device identification

- nvidia/nvidia-graphics-setup
Set NVreg_PreserveVideoMemoryAllocations to enable Wayland for hybrid NVIDIA GPU with gdm 43(+).
https://phabricator.endlessm.com/T35012
> nvidia: Set NVreg_PreserveVideoMemoryAllocations

- Makefile.am
- configure.ac
To achieve this, we will copy the same configuration file that is added
to system.conf.d.
This change is necessary to prevent systemd from stopping the user
session when a child process is killed by the OOM killer. It should be
possible to revert this once Endless OS is using systemd >= v253, where
OOMPolicy defaults to "continue" for login session scopes:
https://github.com/systemd/systemd/commit/98b6c94b577205d31b019286c2a84cc9af244ea0
https://phabricator.endlessm.com/T35041
> T35041 add user manager config

- dracut/repartition/module-setup.sh
`blkid` is used to determine the partition type during repartitioning, but the module wasn't ensuring it was being installed.
https://phabricator.endlessm.com/T35134
> repartition: Ensure blkid is installed

- 60-suspend-mode.rules
- Makefile.am
Mission one cannot resume from S3 suspend by any key press, nor other outside trigger ways. Because the USB is dead. Use s2idle mode to avoid turn off USB when suspend.
https://phabricator.endlessm.com/T35070
> udev: Force Mission one use s2idle suspend mode

- 60-suspend-mode.rules
This fixes commit 6f25d79309d2 ("udev: Force Mission one use s2idle suspend mode") to match DMI correctly.
https://phabricator.endlessm.com/T35246
> udev: Use "==" for comparing, not "=" in the rules

- 50-eos.preset
* disable dpkg-db-backup.timer to avoid triggering dpkg-db-backup.service automatically.
* disable systemd-sysupdate.timer to avoid triggering systemd-sysupdate.service automatically.
https://phabricator.endlessm.com/T35292
> Disable dpkg-db-backup.timer and systemd-sysupdate.timer

- psi-monitor/Makefile.am
- psi-monitor/psi-monitor.c
Get some more information out of `psi-monitor` so we can see what's happening.
https://phabricator.endlessm.com/T35318
> More psi-monitor info

- psi-monitor/psi-monitor.c
This will allow easier experimentation to tune the defaults.
https://phabricator.endlessm.com/T35318
> psi-monitor: Add options to adjust monitoring parameters

- eos-live-boot-overlayfs-setup.service
Systemd ships several units that require access to /var but are not ordered after local-fs.target. It would be better if they did, but that's not the case today. Systemd doesn't expect the kind of mount post-processing that's done here, so order the unit before all of those units.
https://phabricator.endlessm.com/T35323
> overlay-setup: Run before several /var using units

- eos-live-boot-overlayfs-setup
- eos-live-boot-overlayfs-setup.service
Trying to create a list of units that require /var as in 0cddd9e is a losing game. It also doesn't really work properly since you can't order against all instances of a templated unit like foo@.service.
As suggested by upstream[1], the more robust way to handle this is to order the service before var.mount. That requires handling the /var mount in the service, but fortunately that's straightforward for this narrow use case.
With that change, the service will also run before ostree-remount.service, which means it has to take care of marking the /sysroot mount as private. Without that, the /var overlay mount will be mirrored under /sysroot.
1. https://github.com/systemd/systemd/issues/32343
https://phabricator.endlessm.com/T35323
> overlay-setup: Ensure units ordered after /var overlay

- eos-config-journal.service
If eos-config-journal runs after systemd-journal-flush.service then early boot logs may be dropped from memory before journald automatically flushes. Change the ordering to start early after /var is mounted and journald is started but before systemd-journal-flush.service.
https://phabricator.endlessm.com/T35345
> eos-config-journal: Run before systemd-journal-flush.service

- dracut/repartition/endless-repartition.sh
After resizing the main partition, we have the following logic to invoke `partprobe` if it is on a loop device:
if [ -n "$using_loop" ]; then
partprobe $root_disk
udevadm settle
fi
But empirically this block does not run on a fresh dual-boot installation: the kernel still believed the partition has its old size until I manually ran partprobe. As a result eos-firstboot fails to grow the main partition:
eos-firstboot[528]: resize2fs 1.47.0 (5-Feb-2023)
eos-firstboot[528]: The filesystem is already 11053568 (4k) blocks long.  Nothing to do!
$using_loop is conditionally set as follows:
case ${orig_root_part} in
/dev/loop?p?)
using_loop=1
;;
esac
$orig_root_part is set as follows:
orig_root_part=$(systemctl show -p What sysroot.mount)
orig_root_part=${orig_root_part#What=}
I ran this command …
> repartition: Correctly detect rootfs on loop device

- eos-firstboot
- eos-firstboot.service
An alternative approach to https://github.com/endlessm/eos-boot-helper/pull/408.
----
In new dual-boot installs of 6.0.0, eos-firstboot did not correctly grow the filesystem due to the bug fixed in commit
56aea35e497df9d035e8ccf391d9b720de264530.
We now want to run it a second time. Ideally we would only trigger it on affected dual-boot systems; but it is harder to detect that case than to run eos-firstboot again and have resize2fs gracefully do nothing.
While we could easily run a unit only on dual-boot systems with:
ConditionKernelCommandLine=endless.image.device
ConditionKernelCommandLine=!endless.live_boot
to do this only once requires a second unit with its own new flag file. So rather than introducing a second flag file, let's harmlessly re-run this unit once on all systems, and …
> Run eos-firstboot a second time on existing installs

- dracut/repartition/endless-repartition.sh
- dracut/repartition/module-setup.sh
Since da7b937b252bfe5776d3d6ef8902d8fd93453bfd, partprobe in the
initramfs is busybox, not the tool from parted.
For unknown reasons, busybox partprobe fails to probe /dev/loop0 after
it has been repartitioned, failing with:
partprobe: /dev/loop0: Invalid argument
partx --update performs a similar function, except that it works
correctly at this stage of the boot process. Using partx also has the
advantage that running this tool manually from the booted system (where
partprobe is the real thing) will actually run the same code as in the
initramfs.
https://phabricator.endlessm.com/T35432
> repartition: Use partx rather than busybox partprobe

- eos-test-mode
Some systemd services start before execute eos-test-mode. And, if they mount the real storage blocks to /home in their namespace directly, then the modification under /home will be kept, even "test mode" is finished. Therefore, the filesystem is not fresh new for the real end-user.
This commit remounts the eos-live overlays by restarting the systemd services which mount a real storage block to /home in their namespace.
https://phabricator.endlessm.com/T35625
> eos-test-mode: Remount eos-live overlays in some services' namespace

- eos-live-boot-overlayfs-setup
- eos-test-mode
https://phabricator.endlessm.com/T35651
> Test mode cleanups

- eos-live-boot-overlayfs-setup
Overlayfs doesn't support using case insensitive filesystems such as vfat and exfat as a lower directory. Change the mount to read only so changes can't be made there.
In theory this would simply be `mount -o remount,ro`. Unfortunately, if systemd has setup an automount, autofs is not our friend. In that case, the mount options need to be persisted into the mount unit so that a subsequent remounting retains the ro option.
https://phabricator.endlessm.com/T35641
> overlayfs-setup: Fallback to read only mount when overlay not supported

- tmpfiles.d/eos-boot-helper.conf
This reverts part of commit 1338aae7721a5bfddc8b121fb1b761bd779d4313.
Sadly I had not realised that this stamp file was also created by a hook in the image builder. So on every new system installed between 3.5.0 and 6.0.1 inclusive, this stamp file was preinstalled and deleted on first boot; while on all systems installed with 6.0.2 or newer, the stamp file was preinstalled but never removed.
https://github.com/endlessm/eos-image-builder/pull/173 removes the image builder hook, but for the sake of those systems installed with 6.0.2 or newer, reinstate the tmpfiles snippet that deletes the stamp file.
> Partially revert "Remove obsolete cleanup of obsolete stamp files"

- eos-enable-zram
Over prolonged periods, memory allocated to backing zram devices starts to consume more memory, even when pages are unswapped, resulting in increased swappiness and the machine slowing down. Enable discards in the swap layer, so that the backing zram pages can be freed, allowing more hot pages to stay uncompressed.
> eos-enable-zram: Enable swap discards

- Makefile.am
- configure.ac
- journald/Makefile.am
- journald/log.conf
- locale/Makefile.am
- locale/locale.conf
- tmpfiles.d/eos-boot-helper.conf
* journald: Set the maximum on-disk joural size to 50 MiB
* journald: set RuntimeMaxUse=4M by default
* Create locale config file and compat symlink
> Move EOS systemd downstream configs to eos-boot-helper

- 50-eos.preset
- eos-update-efi-uuid.c
This PR adapts eos-boot-helper to work with EOS7, based on GNOME OS. See commits for details, but the breaking changes are:
* Deal with explicit `unsigned char` parameter in efivar (https://github.com/rhboot/efivar/commit/ba165d1482558005a16f4b44abaa1df5169727d1)
* Enable systemd-resolved service
* Remove some initramfs modules that don't exist in EOS7
* Drop systemd preset states for services that don't exist in EOS7
When merged, this will effectively drop support for EOS6 in the 'master' branch.
> Adapt for use in eos7
