endlessm/eos-boot-helper

eos-extra-resize
A few fixes to make resizing of the SD card more robust.
[endlessm/eos-shell#5101]
=> SD card resizing fixes

Makefile.am, debian/eos-boot-helper.dirs, debian/rules, endless-mount-dirs.service, endless.mount, eos-enable-extra-upgrade, eos-enable-extra-upgrade.service, var-endless\x2dextra.mount
=> Always mount /endless as overlay

debian/eos-boot-helper.postinst, debian/rules, endless.mount, eos-enable-extra-upgrade, eos-enable-extra-upgrade.service
=> Fix /var/endless-extra upgrade path

Makefile.am, boot.mount, debian/rules, dracut/repartition/endless-repartition.sh, dracut/repartition/module-setup.sh, eos-extra-resize
https://github.com/endlessm/eos-shell/issues/5331
=> Migrate to GPT/UEFI

Makefile.am, debian/rules, eos-enable-zram, eos-enable-zram.service
=> Enable ZRAM for platforms with <1GB RAM

eos-extra-resize, eos-extra-resize.service
https://github.com/endlessm/eos-shell/issues/6211
=> Fix extra disk resizing race

boot.mount, sysroot-boot.mount
https://phabricator.endlessm.com/T11157
=> T11157: Fix newer systemd un-mounting /boot

debian/eos-boot-helper.postinst, debian/eos-boot-helper.triggers, dracut/endless.conf
https://phabricator.endlessm.com/T11096
https://phabricator.endlessm.com/T4899
=> Update for dracut-044

boot.mount
https://phabricator.endlessm.com/T11374
=> T11374: Fix ordering and add conditionals to control boot.mount execution

eos-enable-zram.service
https://phabricator.endlessm.com/T11405
=> Enable ZRAM also on ARM64

eos-enable-zram.service
https://phabricator.endlessm.com/T11603
=> T11603: zram: Don't start on early boot

dracut/repartition/endless-repartition.sh, eos-firstboot
https://phabricator.endlessm.com/T12003
=> Randomize UUIDs on first boot

dracut/repartition/endless-repartition.sh
The units generated in early boot use paths under /dev/disk/by-uuid/.
Now that we change the root fs UUID on first boot in the initramfs,
those generated units are no longer correct.
It's not possible to tweak the values in the generated units directly,
because you have to run daemon-reload after changing unit files, and
daemon-reload actually re-runs the generators.
However it's quite easy to use systemd's other methods to override unit
file values, which is what we do here.
We make the changes in the initramfs's /etc, which is thrown away when
the kernel switches root. This closely matches what happens to the
generated units too; they are stored in /run which is a mount shared with
the real root, but the generated units are wiped out a moment later when
systemd runs the generators from …
=> repartition: update generated units after changing filesystem UUID

dracut/image-boot/eos-image-boot-setup, dracut/image-boot/module-setup.sh
Relies on ntfsextents tool submitted to ntfs-3g mailing list.
https://phabricator.endlessm.com/T12560
=> image-boot: support NTFS-hosted images too

Makefile.am, eos-repartition-mbr
https://phabricator.endlessm.com/T12793
=> eos-gpt2mbr: Add script to convert GPT to MBR

dracut/repartition/endless-repartition.sh
@dsd @carlocaione – I noticed in passing that this comment is out of date.
=> endless-repartition.sh: update comment for GPT

dracut/repartition/endless-repartition.sh, eos-extra-resize
https://phabricator.endlessm.com/T10685
=> Support MBR on S905x

eos-live-boot-overlayfs-setup
This problem, and its fix, are subtle enough to deserve a small essay in
the script itself.
https://phabricator.endlessm.com/T13975
=> live-boot: fix ostree->flatpak hardlinks

debian/eos-boot-helper.dirs, debian/eos-boot-helper.postinst
https://phabricator.endlessm.com/T13832
=> Do not create /endless directory

debian/eos-boot-helper.postinst
https://phabricator.endlessm.com/T11761
=> debian: We need a recursive rm when deleting directories

eos-enable-extra-upgrade, eos-enable-extra-upgrade.service
Really fix upgrading a split disk system from 2.3.
https://phabricator.endlessm.com/T13889
=> Fix old version split disk upgrading

dracut/repartition/endless-repartition.sh, eos-repartition-mbr
https://phabricator.endlessm.com/T13849
=>  eos-repartition-mbr: leave expanding and swap to first boot 

dracut/endless.conf, dracut/image-boot/module-setup.sh
https://phabricator.endlessm.com/T13557
=> T13557: add support for booting from an ISO image

dracut/repartition/endless-repartition.sh
Asus will start shipping units in China with a recovery partition
added at the end of the disk before Endless first boot.
We can detect this by its GPT partition type UUID and then avoid
deleting it.
Since swap is no longer (always) the final partition we can't
rely on sfdisk making it fill the remaining space, so we need to
calculate and specify it's final size.
https://phabricator.endlessm.com/T14827
=> repartition: don't delete recovery partition at end of disk

dracut/image-boot/eos-image-boot-setup
https://phabricator.endlessm.com/T13557
=> image-boot: Enable iso9660 booting

dracut/image-boot/eos-image-boot-setup
https://phabricator.endlessm.com/T13560
=> ISO: Use squashfs image to mount the root fs

eos-fix-flatpak-branches
Updating the desktop files only is not enough, as the
--branch=<branch> parameter is also present in the Exec
line of D-Bus service files, so fix those ones too.
https://phabricator.endlessm.com/T15005
=> eos-fix-flatpak-branches: Update D-Bus service files too

eos-live-boot-overlayfs-setup
https://phabricator.endlessm.com/T14977
=> live-boot: Avoid errors when the script is called twice

Makefile.am, eos-add-flatpak-gnome-repos, eos-add-flatpak-gnome-repos.service
https://phabricator.endlessm.com/T14665
=> Add GNOME flatpak repositories if needed after an OS upgrade

dracut/image-boot/eos-image-boot-setup
https://phabricator.endlessm.com/T13557
=> ISO: Fix race between udev and eos-image-boot-setup

dracut/image-boot/eos-image-boot-generator
https://phabricator.endlessm.com/T14308
=> ISO: Do not set UDISKS_IGNORE on iso9660 partitions

.gitignore, Makefile.am, configure.ac, debian/control, dracut/image-boot/eos-image-boot-setup, tests/Makefile.am, tests/check-syntax
I've included a patch adding a minimal `make check` implementation, which ought really to be part of a separate pull request…
https://phabricator.endlessm.com/T16428
=> image-boot-setup: fail sooner if mounting squashfs fails

Makefile.am
https://phabricator.endlessm.com/T17172
=> remove eos-flatpak-change-origin from Makefile.am

Makefile.am, configure.ac, eos-live-boot-generator, tests/Makefile.am, tests/test_image_boot.py, tests/test_live_boot_generator.py, tests/util.py
https://phabricator.endlessm.com/T15891
=> live-boot: udevadm settle, don't remount / rw

Makefile.am
https://phabricator.endlessm.com/T15891
=> live-boot: make installed generator executable

dracut/endless.conf
https://phabricator.endlessm.com/T19800
=> dracut: Enable early microcode

tmpfiles.d/avahi-service-writers.conf
https://phabricator.endlessm.com/T20391
=> tmpfiles: Also give group-write permissions to /etc/avahi/services

eos-update-flatpak-repos
gnome-software will update metadata such as title from the repo
summary file after https://github.com/endlessm/gnome-software/pull/314
https://phabricator.endlessm.com/T20328
=> eos-update-flatpak-repos: drop title setting hack

dracut/repartition/endless-repartition.sh
https://phabricator.endlessm.com/T21538
=> endless-repartition.sh: Allow multiple part attrs on rootfs

dracut/repartition/endless-repartition.sh
https://phabricator.endlessm.com/T21538
=> Preserve partition attributes during repartitioning

50-eos.preset
https://phabricator.endlessm.com/T21747
=> eos-preset: Disable OpenVPN by default

eos-fix-flatpak-branches.service, eos-ostree-remotes-config.service, eos-update-flatpak-repos.service
These services all make pretty direct modifications to the ostree repo and flatpak installation configurations. Make sure they run before all relevant services.
https://phabricator.endlessm.com/T22525
=> More ostree/flatpak ordering for repo hacks

eos-update-flatpak-repos
https://phabricator.endlessm.com/T21891
=> eos-update-flatpak-repos: migrate eos-photos to flathub

Makefile.am, debian/control, eos-reclaim-swap, eos-reclaim-swap.service, tests/data/reclaim-swap/gpt-noop-expected.txt, tests/data/reclaim-swap/gpt-noop-input.txt, tests/data/reclaim-swap/gpt-remove-swap-expected.txt, tests/data/reclaim-swap/gpt-remove-swap-input.txt, tests/data/reclaim-swap/gpt-remove-swap-preserving-last-expected.txt, tests/data/reclaim-swap/gpt-remove-swap-preserving-last-input.txt, tests/data/reclaim-swap/mbr-noop-expected.txt, tests/data/reclaim-swap/mbr-noop-input.txt, tests/data/reclaim-swap/mbr-remove-swap-expected.txt, tests/data/reclaim-swap/mbr-remove-swap-input.txt, tests/data/reclaim-swap/mbr-remove-swap-preserving-last-expected.txt, tests/data/reclaim-swap/mbr-remove-swap-preserving-last-input.txt, tests/test_reclaim_swap.py
Find and remove any swap partitions present on the root disk, and expand
the root partition to reclaim that storage space.
https://phabricator.endlessm.com/T22832
=> Reclaim space from swap partition

eos-update-flatpak-repos
https://phabricator.endlessm.com/T23681
=> eos-update-flatpak-repos: migrate Stellarium to flathub

eos-update-flatpak-repos, tests/test_update_flatpak_repos.py
https://phabricator.endlessm.com/T23856
=> eos-update-flatpak-repos: configure mass migration of eos-apps to flathub

eos-update-flatpak-repos, tests/test_repartition.py, tests/test_repartition_mbr.py, tests/test_update_flatpak_repos.py
See commit messages for the gory details.
https://phabricator.endlessm.com/T23856
=> eos-update-flatpak-repos: handle vendor-prefixed .desktop files

eos-update-flatpak-repos
https://phabricator.endlessm.com/T23856
=> T23856: fixups for 2->1 and no-rename migrations

50-eos.preset, Makefile.am, configure.ac, factory-reset/Makefile.am, factory-reset/eos-factory-reset, factory-reset/eos-factory-reset-users, factory-reset/eos-factory-reset-users.service
Add an initial version of a factory reset framework, with one simple stage that removes all user accounts and home directories from the system.
https://phabricator.endlessm.com/T24613
=> Factory reset

50-eos.preset, Makefile.am, configure.ac, factory-reset/Makefile.am, factory-reset/eos-factory-reset, factory-reset/eos-factory-reset-users, factory-reset/eos-factory-reset-users.service
Add an initial version of a factory reset framework, with one simple stage that removes all user accounts and home directories from the system.
This is the eos3.5-specific PR.
https://phabricator.endlessm.com/T24613
=> Factory reset eos3.5

eos-update-flatpak-repos
https://phabricator.endlessm.com/T26588
=> migrate Minecraft to flathub

eos-update-flatpak-repos
https://phabricator.endlessm.com/T26658
=> eos-update-flatpak-repos: Migrate Scratch to flathub

eos-update-flatpak-repos
https://phabricator.endlessm.com/T25928
=> eos-update-flatpak-repos: Migrate endlessnetwork apps

dracut/image-boot/eos-image-boot-setup
https://phabricator.endlessm.com/T27158
=> image-boot-setup: fix issues with new repartitioning setup

eos-update-flatpak-repos
https://phabricator.endlessm.com/T28386
=> T28386: migrate Etoys to Flathub

eos-update-flatpak-repos
https://phabricator.endlessm.com/T28707
=> eos-update-flatpak-repos: Migrate Eclipse to Flathub

eos-live-boot-generator
https://phabricator.endlessm.com/T30599
=> live-generator: Allow Kolibri to access KOLIBRI_HOME

tmpfiles.d/flatpak-extension-kiwix-usb-content.conf
https://phabricator.endlessm.com/T30599
=> live: Fix architecture in Encyclopedia transient extension

dracut/endless.conf
This removes some GPLv3 software from initrd to meet our PAYG
requirements.
https://phabricator.endlessm.com/T30878
=> dracut: Use busybox for sed and coreutils

eos-update-flatpak-repos
These are cherry-picks from the eos3.3 branch.
https://phabricator.endlessm.com/T31079
=> T31079 Forwardport runtime migrations

eos-split-flatpak-repo.service
https://phabricator.endlessm.com/T31877
=> eos-split-flatpak-repo: Fix typo in service file

.github/workflows/block-autosquash-commits.yml
https://phabricator.endlessm.com/T27163
=> Fail CI if autosquash commits are present

Makefile.am, eos-transient-setup, eos-transient-setup.service
This is your new home, little friend. It fits you
better. It's comfy, and you may notice you now
have new friends that look almost like you.
Enjoy your stay.
https://phabricator.endlessm.com/T32043
=> Add eos-transient-setup{,.service}

Makefile.am, eos-migrate-shotwell.service
Worked in my initial testing - but somehow I broke flatpak shotwell's ability to install (unrelated building of it). 
Thoughts on this approach?
https://phabricator.endlessm.com/T31431
=> Simple systemd service to migrate shotwell to flatpak

eos-split-flatpak-repo
A couple fixes to try to speed up splitting up large repos.
https://phabricator.endlessm.com/T32768
=> split-flatpak-repo speedups

10-eos-oom-policy.conf, Makefile.am, configure.ac
https://phabricator.endlessm.com/T35041
=> Override DefaultOOMPolicy in system.conf.d
